apiVersion: "v1"
kind: "Service"
metadata:
  name: "dataserver-memsql-service"
  namespace: "default"
  labels:
    env: "production"
    layer: "dataserver-memsql"
    project: "factors-production"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8089
  selector:
    layer: "dataserver-memsql"
  type: "ClusterIP"