apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    app: etcd
    env: production
    project: factors-production
spec:
  ports:
  - protocol: TCP
    port: 2379
    targetPort: 2379
  clusterIP: None
  selector:
    app: etcd