apiVersion: v1
kind: Service
metadata:
  name: etcd-ilb
  namespace: default
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    env: "production"
    project: "factors-production"
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: etcd-0
  ports:
  - port: 2379
    targetPort: 2379
    protocol: TCP