apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
    env: production
    project: factors-production
  name: frontend-service
  namespace: default  
spec:
  ports:
  - nodePort: 31979
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: frontend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}