FROM jmfirth/webpack:latest

WORKDIR /frontend
ENV NODE_ENV='development'
COPY . .
RUN rm -rf ./dist/staging
RUN npm install
RUN npm rebuild node-sass
RUN cp -r  ./src/views/Settings ./src/views/settings
RUN ./node_modules/.bin/webpack -p --config webpack.config.js
RUN mv ./dist/development/* ./dist
RUN npm install express 
EXPOSE 3000
CMD ["node", "serve-dist.js"]