export const FUNNEL_RESULTS_AVAILABLE = 'FUNNEL_RESULTS_AVAILABLE';
export const FUNNEL_RESULTS_UNAVAILABLE = 'FUNNEL_RESULTS_UNAVAILABLE';
export const SET_PROJECTS = 'SET_PROJECTS';
export const SET_ACTIVE_PROJECT = 'SET_ACTIVE_PROJECT';
