APP_NAME = 'linkedin_sync'
CAMPAIGN_GROUP_INSIGHTS = 'campaign_group_insights'
CAMPAIGN_INSIGHTS = 'campaign_insights'
CREATIVE_INSIGHTS = 'creative_insights'
MEMBER_COMPANY_INSIGHTS = 'member_company_insights'
CAMPAIGN = 'campaign'
CAMPAIGNS = 'campaign'
CREATIVES = 'creative'
CAMPAIGN_GROUPS = 'campaign_group'
AD_ACCOUNT = 'ad_account'
ACCESS_TOKEN = 'int_linkedin_access_token'
REFRESH_TOKEN = 'int_linkedin_refresh_token'
LINKEDIN_AD_ACCOUNT = 'int_linkedin_ad_account'
ELEMENTS = 'elements'
PROJECT_ID = 'project_id'
CAMPAIGN_GROUP_ID = 'campaign_group_id'
CAMPAIGN_ID = 'campaign_id'
CREATIVE_ID = 'creative_id'
MAX_LOOKBACK = 30
API_REQUESTS = 'api_requests'
META_COUNT = 100
INSIGHTS_COUNT = 10000
BATCH_SIZE = 1000
BACKFILL_DAY = 8
META_DATA_URL = 'https://api.linkedin.com/v2/{}?q=search&search.account.values[0]=urn:li:sponsoredAccount:{}&start={}&count={}'
INSIGHTS_REQUEST_URL_FORMAT = 'https://api.linkedin.com/v2/adAnalyticsV2?q=analytics&pivot={}&dateRange.start.day={}&dateRange.start.month={}&dateRange.start.year={}&dateRange.end.day={}&dateRange.end.month={}&dateRange.end.year={}&timeGranularity=DAILY&fields={}&accounts[0]=urn:li:sponsoredAccount:{}&start={}&count={}'
REQUESTED_FIELDS='totalEngagements,impressions,clicks,dateRange,landingPageClicks,costInUsd,leadGenerationMailContactInfoShares,leadGenerationMailInterestedClicks,opens,videoCompletions,videoFirstQuartileCompletions,videoMidpointCompletions,videoThirdQuartileCompletions,videoViews,externalWebsiteConversions,externalWebsitePostClickConversions,externalWebsitePostViewConversions,costInLocalCurrency,conversionValueInLocalCurrency,pivotValue'
ORG_LOOKUP_URL = 'https://api.linkedin.com/v2/organizationsLookup?ids=List({})'
AD_ACCOUNT_URL = 'https://api.linkedin.com/v2/adAccountsV2/{}'
FETCH_LOG_WITH_DOC_TYPE = 'Fetching {} started for project {} for timestamp {}'
NUM_OF_RECORDS_LOG = 'No of {} records to be inserted for project {} : {}'
API_ERROR_FORMAT = 'Failed to get {} {} from linkedin. StatusCode: {}. Error: {}. Project_id: {}. Ad Account: {}'
DOC_INSERT_ERROR = 'Failed to insert {} {} in database. StatusCode: {}. Error: {}. Project_id: {}. Ad Account: {}. Timestamp: {}'
META_FETCH_START = 'Fetching metadata for {} started for project {}'
INSERTION_LOG = 'Inserting {} {} for timestamp {}'
INSERTION_END_LOG = 'Inserting {} {} ended for timestamp {}'
FINAL_INSERTION_END_LOG = 'Inserting {} {} ended for project {}'
NO_DATA_MEMBER_COMPANY_LOG = 'No data found for member company insights for project {} and Ad account {}'
ACCESS_TOKEN_CHECK_URL = 'https://api.linkedin.com/v2/me?oauth2_access_token={}'
TOKEN_GENERATION_URL = 'https://www.linkedin.com/oauth/v2/accessToken?grant_type=refresh_token&refresh_token={}&client_id={}&client_secret={}'
METRIC_TYPE_INCR = 'incr'
HEALTHCHECK_PING_ID = '837dce09-92ec-4930-80b3-831b295d1a34'
HEALTHCHECK_TOKEN_FAILURE_PING_ID = 'b231cf93-ce7e-4df6-9416-1797c5065c22'
URL_ENDPOINT_CAMPAIGN_GROUP_META = 'adCampaignGroupsV2'
URL_ENDPOINT_CAMPAIGN_META = 'adCampaignsV2'
URL_ENDPOINT_CREATIVE_META = 'adCreativesV2'
BACKFILL_NOT_REQUIRED = "Backfill not required for %s for project %s for ad account %s"
AD_ACCOUNT_FAILURE = 'Failed to get ad_accounts metadata from linkedin'
ORG_DATA_FETCH_ERROR = "Failed getting organisation data with error {}"