apiVersion: v1
kind: Service
metadata:
  labels:
    layer: appserver
    env: staging
    project: factors-staging
  name: appserver-service
  namespace: default
spec:    
  ports:
  - nodePort: 31074
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    layer: appserver
  sessionAffinity: None
  type: NodePort