apiVersion: v1
kind: Service
metadata:
  labels:
    layer: appserver-memsql
    env: staging
    project: factors-staging
  name: appserver-service-memsql
  namespace: default
spec:    
  ports:
  - nodePort: 31076
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    layer: appserver-memsql
  sessionAffinity: None
  type: NodePort
