apiVersion: "v1"
kind: "Service"
metadata:
  name: "dataserver-service"
  namespace: "default"
  labels:
    env: "staging"
    layer: "dataserver"
    project: "factors-staging"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8089
  selector:
    layer: "dataserver"
  type: "ClusterIP"