apiVersion: "v1"
kind: "Service"
metadata:
  name: "queue-redis-2-service"
  namespace: "default"
  labels:
    env: "staging"
    layer: "queue-redis-2"
    project: "factors-staging"
spec:
  ports:
  - protocol: "TCP"
    port: 9379 # Using different port.
    targetPort: 6379
  selector:
    layer: "queue-redis-2"
  sessionAffinity: None
  type: "ClusterIP"