apiVersion: "v1"
kind: "Service"
metadata:
  name: "persistent-redis-service"
  namespace: "default"
  labels:
    env: "staging"
    layer: "persistent-redis"
    project: "factors-staging"
spec:
  ports:
  - protocol: "TCP"
    port: 8379 # Using different port.
    targetPort: 6379
  selector:
    layer: "persistent-redis"
  sessionAffinity: None
  type: "ClusterIP"