apiVersion: "v1"
kind: "Service"
metadata:
  name: "redis-service"
  namespace: "default"
  labels:
    env: "staging"
    layer: "redis"
    project: "factors-staging"
spec:
  ports:
  - protocol: "TCP"
    port: 6379
    targetPort: 6379
  selector:
    layer: "redis"
  sessionAffinity: None
  type: "ClusterIP"