apiVersion: v1
kind: Service
metadata:
  labels:
    layer: sdkserver
    env: staging
    project: factors-staging
  name: sdkserver-service
  namespace: default
spec:    
  ports:
  - nodePort: 31075
    port: 80
    protocol: TCP
    targetPort: 8085
  selector:
    layer: sdkserver
  sessionAffinity: None
  type: NodePort