version: '3'

services:
        memsql:
            build:
                context: .
                dockerfile: Dockerfile.memsql.testing
                args:
                    - MEMSQL_VERSION=alma-7.6.13-39da2f5c72-4.0.4-1.13.6
            image: testing/memsql:1.0
            restart: always
            environment:
                - LICENSE_KEY=$MEMSQL_LICENSE_KEY
                - ROOT_PASSWORD=$ROOT_PASSWORD
                - START_AFTER_INIT='Y'
            ports:
                - 3306:3306
                - 8040:8080
        redis:  
            build:
                context: ../
                dockerfile: Dockerfile.redis
            image: testing/redis:1.0
            restart: always
            ports:
                - "6379:6379"
        etcd:
            image: 'bitnami/etcd:latest'
            environment:
                - ALLOW_NONE_AUTHENTICATION=yes
                - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
            ports:
                - 2379:2379
                - 2380:2380
        builddb:
            build:
                context: ../
                dockerfile: docker-development-setup/Dockerfile.db_create.testing
            environment:
                - PRI_DS=memsql
                - ROOT_PASSWORD=$ROOT_PASSWORD
            image: testing/builddb:1.0
            depends_on:
                - memsql
        api:
            build:
                context: ../
                dockerfile: Dockerfile.appserver
            environment:
                -  GOPATH=/go/src/factors
                -  REDIS_HOST=redis
                -  ETCD=etcd:2379
                -  PS=patternserver
                -  PRI_DS=memsql
            entrypoint: [ "sh","-c","/go/bin/app --redis_host_ps=redis --dup_queue_redis_host=redis --queue_redis_host=redis --etcd=etcd:2379 --api_domain=$API_DOMAIN --env=development --memsql_host=memsql --primary_datastore=memsql"]
            image: testing/api:1.0
            restart: always
            ports:
                - "8080:8080"
            volumes: 
                - ../../../geolocation_data:/usr/local/var/factors/geolocation_data
                - ../../../devicedetector_data:/usr/local/var/factors/devicedetector_data
            depends_on:
                - memsql
                - etcd
                - redis
        sdkserver:
            build:
                context: ../
                dockerfile: docker-development-setup/Dockerfile.sdkserver.testing
            environment:
                -  GOPATH=/go/src/factors
                -  REDIS_HOST=redis
                -  MEMSQL_HOST=memsql
            entrypoint: [ "sh","-c","/go/bin/sdkserver --redis_host=redis --redis_host_ps=redis --dup_queue_redis_host=redis --queue_redis_host=redis --env=development --memsql_host=memsql --primary_datastore=memsql"]
            image: testing/sdk:1.0
            ports:
                - "8085:8085"
            restart: always
            volumes: 
                - ../../../geolocation_data:/usr/local/var/factors/geolocation_data
                - ../../../devicedetector_data:/usr/local/var/factors/devicedetector_data
            depends_on:
                - memsql
                - redis
        patternserver:
            build:
                context: ../
                dockerfile: docker-development-setup/Dockerfile.patternserver.testing
            environment:
                -   GOPATH=/go/src/factors
                -   ETCD=etcd:2379
                -   MEMSQL_HOST=memsql
            image: testing/pattern-server:1.0
            ports:
                - "8100:8100"
            depends_on:
                - memsql
                - etcd
                - redis
        # Frontend docker is not building. Run manually.
        #frontend:
        #    build: 
        #        context: ../../../frontend-new
        #        dockerfile: Dockerfile.frontend.testing
        #    image: testing/frontend:1.0
        #    ports: 
        #        - "3000:3000"
        datagen:
            build:
                context: ../../../misc/data_simulator/src/
                dockerfile: Dockerfile.data_gen.testing
            environment:
                - CONFIG=acme_com
                - AUTH_TOKEN=78ycpg9dsgok7o4dbk58jtl2rgt0tg0o
                - SDK_HOST=sdkserver
                - ENV=docker
                - SEED_DATE=$SEED_DATE
            image: testing/datagen:1.0
            depends_on:
                - sdkserver
        session:
            build:
                context: ../
                dockerfile: docker-development-setup/Dockerfile.session.testing
            environment:
                - REDIS_HOST=redis
                - MEMSQL_HOST=memsql
                - PRI_DS=memsql
            image: testing/session:1.0
        rollupcache:
            build:
                context: ../
                dockerfile: docker-development-setup/Dockerfile.rollup_cache.testing
            environment:
                - REDIS_HOST=redis
                - MEMSQL_HOST=memsql
                - PRI_DS=memsql
            image: testing/rollupcache:1.0
        # Needs to be fixed.
        #documentdatagen:
        #    build:
        #        context: ../
        #        dockerfile: docker-development-setup/Dockerfile.documentdatagen.testing
        #    environment:
        #        - MEMSQL_HOST=memsql
        #        - PRI_DS=memsql
        #    image: testing/documentdatagen:1.0
        #    depends_on:
        #        - sdkserver
