FROM golang:1.20.3-alpine AS builder

ENV GOPATH /go
WORKDIR /go/src/factors
ADD /factors .
RUN go build -o /go/src/factors/backend/bin/session scripts/run_add_session/run_add_session.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && apk add curl && rm -rf /var/cache/apk/*
COPY --from=builder /go/src/factors/backend/bin/session /go/src/factors/backend/bin/session
CMD ["sh","-c", "/go/src/factors/backend/bin/session  --primary_datastore=${PRI_DS} --memsql_host=${MEMSQL_HOST} --db_host=${DB_HOST} --redis_host_ps=${REDIS_HOST}"]