FROM golang:1.14-alpine AS builder

ENV GOPATH /go
WORKDIR /go/src/factors
ADD /factors .
RUN go build -o /go/src/factors/backend/bin/rollupcache scripts/run_rollup_sortedset_cache/run_rollup_sortedset_cache.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && apk add curl && rm -rf /var/cache/apk/*
COPY --from=builder /go/src/factors/backend/bin/rollupcache /go/src/factors/backend/bin/rollupcache
CMD ["sh","-c", "/go/src/factors/backend/bin/rollupcache --primary_datastore=${PRI_DS} --memsql_host=${MEMSQL_HOST} --db_host=${DB_HOST} --redis_host_ps=${REDIS_HOST}"]