package default_data

import (
	"factors/model/model"
	"net/http"

	log "github.com/sirupsen/logrus"
)

var defaultHubspotCustomKPIs = []model.CustomMetric{
	{
		Name:        model.HubspotContacts,
		Description: "Hubspot Contacts timestamped at Contact Create Date",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        model.HubspotMQLDateEntered,
		Description: "HubSpot MQLs (Date Entered Stage)",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        model.HubspotSQLDateEntered,
		Description: "HubSpot SQLs (Date Entered Stage)",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        model.HubspotContactsCreatedDate,
		Description: "HubSpot MQLs (Contact Create Date)",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        model.HubspotContactSQLCreatedDate,
		Description: "HubSpot SQLs (Contact Create Date)",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        model.HubspotOppCreatedDate,
		Description: "HubSpot Opps (Contact Create Date)",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        model.HubspotCustomersCreatedDate,
		Description: "HubSpot Customers (Contact Create Date)",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        model.HubspotMQLMqlDate,
		Description: "HubSpot MQLs (MQL Date)",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        model.HubspotSQLSqlDate,
		Description: "HubSpot SQLs (SQL Date)",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        model.HubspotOppsOppDate,
		Description: "HubSpot Opps (Opp Date)",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        model.HubspotCustomersCustomerDate,
		Description: "HubSpot Customers (Customer Date)",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        model.HubspotDeals,
		Description: "Deals",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotDealsDisplayCategory,
	},
	{
		Name:        model.HubspotPipeline,
		Description: "Pipeline",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotDealsDisplayCategory,
	},
	{
		Name:        model.HubspotRevenue,
		Description: "Revenue",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotDealsDisplayCategory,
	},
	{
		Name:        model.HubspotAvgDealSize,
		Description: "Avg Deal size",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotDealsDisplayCategory,
	},
	{
		Name:        model.HubspotClosedWonDeals,
		Description: "Closed  Won Deals",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotDealsDisplayCategory,
	},
	{
		Name:        model.HubspotClosedWonDealsCreatedDate,
		Description: "Closed won Deals (Create Date)",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotDealsDisplayCategory,
	},
	{
		Name:        model.HubspotAvgSalesCycleLength,
		Description: "Hubspot Avg Sales Cycle Length",
		TypeOfQuery: 1,
		MetricType:  model.DateTypeDiffMetricType,
		ObjectType:  model.HubspotDealsDisplayCategory,
	},
	{
		Name:        model.HubspotMQLToSQL,
		Description: "Sum of SQLs divided by Sum of MQLs by cohort of Contact Create Date",
		TypeOfQuery: 2,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        model.HubspotSQLToOpp,
		Description: "Sum of Opps divided by Sum of SQLs by cohort of Contact Create Date",
		TypeOfQuery: 2,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        model.HubspotOppsToCustomer,
		Description: "Sum of Customers divided by Sum of Opps by cohort of Contact Create Date",
		TypeOfQuery: 2,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:            model.HubspotClosedRate,
		Description:     "For segment level KPIs (HubSpot)",
		TypeOfQuery:     2,
		ObjectType:      model.HubspotDealsDisplayCategory,
		DisplayResultAs: model.MetricsPercentageType,
	},
}

var defaultHubspotCustomKPITransformations = []model.CustomMetricTransformation{
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters:               []model.KPIFilter{},
		DateField:             "$hubspot_contact_createdate",
		EventName:             "",
		Entity:                model.UserEntity,
	},
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "marketingqualifiedlead",
				LogicalOp:        "AND",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "salesqualifiedlead",
				LogicalOp:        "OR",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "opportunity",
				LogicalOp:        "OR",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "customer",
				LogicalOp:        "OR",
			},
		},
		DateField: "$hubspot_contact_hs_date_entered_marketingqualifiedlead",
		EventName: "",
		Entity:    model.UserEntity,
	},
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "salesqualifiedlead",
				LogicalOp:        "AND",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "opportunity",
				LogicalOp:        "OR",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "customer",
				LogicalOp:        "OR",
			},
		},
		DateField: "$hubspot_contact_hs_date_entered_salesqualifiedlead",
		EventName: "",
		Entity:    model.UserEntity,
	},
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "marketingqualifiedlead",
				LogicalOp:        "AND",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "salesqualifiedlead",
				LogicalOp:        "OR",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "opportunity",
				LogicalOp:        "OR",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "customer",
				LogicalOp:        "OR",
			},
		},
		DateField: "$hubspot_contact_createdate",
		EventName: "",
		Entity:    model.UserEntity,
	},
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "salesqualifiedlead",
				LogicalOp:        "AND",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "opportunity",
				LogicalOp:        "OR",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "customer",
				LogicalOp:        "OR",
			},
		},
		DateField: "$hubspot_contact_createdate",
		EventName: "",
		Entity:    model.UserEntity,
	},
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "opportunity",
				LogicalOp:        "AND",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "customer",
				LogicalOp:        "OR",
			},
		},
		DateField: "$hubspot_contact_createdate",
		EventName: "",
		Entity:    model.UserEntity,
	},
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "customer",
				LogicalOp:        "AND",
			},
		},
		DateField: "$hubspot_contact_createdate",
		EventName: "",
		Entity:    model.UserEntity,
	},
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "marketingqualifiedlead",
				LogicalOp:        "AND",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "salesqualifiedlead",
				LogicalOp:        "OR",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "opportunity",
				LogicalOp:        "OR",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "customer",
				LogicalOp:        "OR",
			},
		},
		DateField: "$hubspot_contact_hs_lifecyclestage_marketingqualifiedlead_date",
		EventName: "",
		Entity:    model.UserEntity,
	},
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "salesqualifiedlead",
				LogicalOp:        "AND",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "opportunity",
				LogicalOp:        "OR",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "customer",
				LogicalOp:        "OR",
			},
		},
		DateField: "$hubspot_contact_hs_lifecyclestage_salesqualifiedlead_date",
		EventName: "",
		Entity:    model.UserEntity,
	},
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "opportunity",
				LogicalOp:        "AND",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "customer",
				LogicalOp:        "OR",
			},
		},
		DateField: "$hubspot_contact_hs_lifecyclestage_opportunity_date",
		EventName: "",
		Entity:    model.UserEntity,
	},
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "customer",
				LogicalOp:        "AND",
			},
		},
		DateField: "$hubspot_contact_hs_lifecyclestage_customer_date",
		EventName: "",
		Entity:    model.UserEntity,
	},
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters:               []model.KPIFilter{},
		DateField:             "$hubspot_deal_createdate",
		EventName:             "",
		Entity:                model.UserEntity,
	},
	{
		AggregateFunction:     model.SumAggregateFunction,
		AggregateProperty:     "$hubspot_deal_amount",
		AggregatePropertyType: "categorical",
		Filters:               []model.KPIFilter{},
		DateField:             "$hubspot_deal_createdate",
		EventName:             "",
		Entity:                model.UserEntity,
	},
	{
		AggregateFunction:     model.SumAggregateFunction,
		AggregateProperty:     "$hubspot_deal_amount",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_deal_dealstage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "closedwon",
				LogicalOp:        "AND",
			},
		},
		DateField: "$hubspot_deal_hs_v2_date_entered_closedwon",
		EventName: "",
		Entity:    model.UserEntity,
	},
	{
		AggregateFunction:     model.AverageAggregateFunction,
		AggregateProperty:     "$hubspot_deal_amount",
		AggregatePropertyType: "categorical",
		Filters:               []model.KPIFilter{},
		DateField:             "$hubspot_deal_createdate",
		EventName:             "",
		Entity:                model.UserEntity,
	},
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_deal_dealstage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "closedwon",
				LogicalOp:        "AND",
			},
		},
		DateField: "$hubspot_deal_hs_v2_date_entered_closedwon",
		EventName: "",
		Entity:    model.UserEntity,
	},
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_deal_dealstage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "closedwon",
				LogicalOp:        "AND",
			},
		},
		DateField: "$hubspot_deal_createdate",
		EventName: "",
		Entity:    model.UserEntity,
	},
	{
		AggregateFunction:      model.AverageAggregateFunction,
		AggregateProperty:      "$hubspot_deal_createdate",
		AggregatePropertyType:  "datetime",
		AggregateProperty2:     "$hubspot_deal_hs_date_entered_closedwon",
		AggregatePropertyType2: "datetime",
		Filters:                []model.KPIFilter{},
		DateField:              "$hubspot_deal_hs_date_entered_closedwon",
		EventName:              "",
		Entity:                 model.UserEntity,
	},
}

var defaultHubspotDerivedKPITransformations = []model.KPIQueryGroup{
	{
		Class: model.QueryClassKPI,
		Queries: []model.KPIQuery{
			{
				Category:         model.ProfileCategory,
				DisplayCategory:  model.HubspotContactsDisplayCategory,
				Metrics:          []string{"HubSpot SQLs (Contact Create Date)"},
				Filters:          []model.KPIFilter{},
				GroupBy:          []model.KPIGroupBy{},
				GroupByTimestamp: "",
				Timezone:         "",
				Operator:         "",
				QueryType:        "",
				Name:             "a",
			},
			{
				Category:         model.ProfileCategory,
				DisplayCategory:  model.HubspotContactsDisplayCategory,
				Metrics:          []string{"HubSpot MQLs (Contact Create Date)"},
				Filters:          []model.KPIFilter{},
				GroupBy:          []model.KPIGroupBy{},
				GroupByTimestamp: "",
				Timezone:         "",
				Operator:         "",
				QueryType:        "",
				Name:             "b",
			},
		},
		GlobalFilters: []model.KPIFilter{},
		GlobalGroupBy: []model.KPIGroupBy{},
		Formula:       "a/b",
	},
	{
		Class: model.QueryClassKPI,
		Queries: []model.KPIQuery{
			{
				Category:         model.ProfileCategory,
				DisplayCategory:  model.HubspotContactsDisplayCategory,
				Metrics:          []string{"HubSpot Opps (Contact Create Date)"},
				Filters:          []model.KPIFilter{},
				GroupBy:          []model.KPIGroupBy{},
				GroupByTimestamp: "",
				Timezone:         "",
				Operator:         "",
				QueryType:        "",
				Name:             "a",
			},
			{
				Category:         model.ProfileCategory,
				DisplayCategory:  model.HubspotContactsDisplayCategory,
				Metrics:          []string{"HubSpot SQLs (Contact Create Date)"},
				Filters:          []model.KPIFilter{},
				GroupBy:          []model.KPIGroupBy{},
				GroupByTimestamp: "",
				Timezone:         "",
				Operator:         "",
				QueryType:        "",
				Name:             "b",
			},
		},
		GlobalFilters: []model.KPIFilter{},
		GlobalGroupBy: []model.KPIGroupBy{},
		Formula:       "a/b",
	},
	{
		Class: model.QueryClassKPI,
		Queries: []model.KPIQuery{
			{
				Category:         model.ProfileCategory,
				DisplayCategory:  model.HubspotContactsDisplayCategory,
				Metrics:          []string{"HubSpot Customers (Contact Create Date)"},
				Filters:          []model.KPIFilter{},
				GroupBy:          []model.KPIGroupBy{},
				GroupByTimestamp: "",
				Timezone:         "",
				Operator:         "",
				QueryType:        "",
				Name:             "a",
			},
			{
				Category:         model.ProfileCategory,
				DisplayCategory:  model.HubspotContactsDisplayCategory,
				Metrics:          []string{"HubSpot Opps (Contact Create Date)"},
				Filters:          []model.KPIFilter{},
				GroupBy:          []model.KPIGroupBy{},
				GroupByTimestamp: "",
				Timezone:         "",
				Operator:         "",
				QueryType:        "",
				Name:             "b",
			},
		},
		GlobalFilters: []model.KPIFilter{},
		GlobalGroupBy: []model.KPIGroupBy{},
		Formula:       "a/b",
	},
	{
		Class: model.QueryClassKPI,
		Queries: []model.KPIQuery{
			{
				Category:         model.ProfileCategory,
				DisplayCategory:  model.HubspotDealsDisplayCategory,
				Metrics:          []string{model.HubspotClosedWonDealsCreatedDate},
				Filters:          []model.KPIFilter{},
				GroupBy:          []model.KPIGroupBy{},
				GroupByTimestamp: "",
				Timezone:         "",
				Operator:         "",
				QueryType:        "",
				Name:             "a",
			},
			{
				Category:         model.ProfileCategory,
				DisplayCategory:  model.HubspotDealsDisplayCategory,
				Metrics:          []string{model.HubspotDeals},
				Filters:          []model.KPIFilter{},
				GroupBy:          []model.KPIGroupBy{},
				GroupByTimestamp: "",
				Timezone:         "",
				Operator:         "",
				QueryType:        "",
				Name:             "b",
			},
		},
		GlobalFilters: []model.KPIFilter{},
		GlobalGroupBy: []model.KPIGroupBy{},
		Formula:       "a/b",
	},
}

type BuildDefaultHubspotCustomKPI struct {
}

func (buildDefault BuildDefaultHubspotCustomKPI) Build(projectID int64) int {
	if !CheckIfDefaultHubspotDatasAreCorrect() {
		log.Warn("Failed because defaultDatas and transformations are of incorrect length.")
		return http.StatusInternalServerError
	}
	return buildForCustomKPI(projectID, defaultHubspotCustomKPIs, defaultHubspotCustomKPITransformations, defaultHubspotDerivedKPITransformations)
}

func CheckIfDefaultHubspotDatasAreCorrect() bool {
	return len(defaultHubspotCustomKPIs) == (len(defaultHubspotCustomKPITransformations) + len(defaultHubspotDerivedKPITransformations))
}
