package default_data

import (
	"factors/model/model"
	"net/http"

	log "github.com/sirupsen/logrus"
)

var defaultHubspotCustomKPIs = []model.CustomMetric{
	{
		Name:        "Hubspot Contacts",
		Description: "Hubspot Contacts timestamped at Contact Create Date",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        "HubSpot MQLs (Contact Create Date)",
		Description: "HubSpot MQLs (Contact Create Date)",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        "HubSpot SQLs (Contact Create Date)",
		Description: "HubSpot SQLs (Contact Create Date)",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        "HubSpot Opps (Contact Create Date)",
		Description: "HubSpot Opps (Contact Create Date)",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        "HubSpot Customers (Contact Create Date)",
		Description: "HubSpot Customers (Contact Create Date)",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        "HubSpot MQLs (MQL Date)",
		Description: "HubSpot MQLs (MQL Date)",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        "HubSpot SQLs (SQL Date)",
		Description: "HubSpot SQLs (SQL Date)",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        "HubSpot Opps (Opp Date)",
		Description: "HubSpot Opps (Opp Date)",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        "HubSpot Customers (Customer Date)",
		Description: "HubSpot Customers (Customer Date)",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        "HubSpot Overall Deals",
		Description: "HubSpot Overall Deals",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotDealsDisplayCategory,
	},
	{
		Name:        "HubSpot Overall Pipeline",
		Description: "HubSpot Overall Pipeline",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotDealsDisplayCategory,
	},
	{
		Name:        "HubSpot Overall Closed Won Deals (Deal Create Date)",
		Description: "HubSpot Overall Closed Won Deals (Deal Create Date)",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        "HubSpot Overall Closed Won Revenue (Deal Create Date)",
		Description: "HubSpot Overall Closed Won Revenue (Deal Create Date)",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        "HubSpot Overall Closed Won Deals (Close Date)",
		Description: "HubSpot Overall Closed Won Deals (Close Date)",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        "HubSpot Overall Closed Won Revenue (Close Date)",
		Description: "HubSpot Overall Closed Won Revenue (Close Date)",
		TypeOfQuery: 1,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        "Hubspot MQLs to SQLs (Contact Create Date)",
		Description: "Sum of SQLs divided by Sum of MQLs by cohort of Contact Create Date",
		TypeOfQuery: 2,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        "Hubspot SQLs to Opps (Contact Create Date)",
		Description: "Sum of Opps divided by Sum of SQLs by cohort of Contact Create Date",
		TypeOfQuery: 2,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
	{
		Name:        "Hubspot Opps to Customer (Contact Create Date)",
		Description: "Sum of Customers divided by Sum of Opps by cohort of Contact Create Date",
		TypeOfQuery: 2,
		ObjectType:  model.HubspotContactsDisplayCategory,
	},
}

var defaultHubspotCustomKPITransformations = []model.CustomMetricTransformation{
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters:               []model.KPIFilter{},
		DateField:             "$hubspot_contact_createdate",
		EventName:             "",
		Entity:                model.UserEntity,
	},
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "marketingqualifiedlead",
				LogicalOp:        "AND",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "salesqualifiedlead",
				LogicalOp:        "OR",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "opportunity",
				LogicalOp:        "OR",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "customer",
				LogicalOp:        "OR",
			},
		},
		DateField: "$hubspot_contact_createdate",
		EventName: "",
		Entity:    model.UserEntity,
	},
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "salesqualifiedlead",
				LogicalOp:        "AND",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "opportunity",
				LogicalOp:        "OR",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "customer",
				LogicalOp:        "OR",
			},
		},
		DateField: "$hubspot_contact_createdate",
		EventName: "",
		Entity:    model.UserEntity,
	},
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "opportunity",
				LogicalOp:        "AND",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "customer",
				LogicalOp:        "OR",
			},
		},
		DateField: "$hubspot_contact_createdate",
		EventName: "",
		Entity:    model.UserEntity,
	},
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "customer",
				LogicalOp:        "AND",
			},
		},
		DateField: "$hubspot_contact_createdate",
		EventName: "",
		Entity:    model.UserEntity,
	},
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "marketingqualifiedlead",
				LogicalOp:        "AND",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "salesqualifiedlead",
				LogicalOp:        "OR",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "opportunity",
				LogicalOp:        "OR",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "customer",
				LogicalOp:        "OR",
			},
		},
		DateField: "$hubspot_contact_hs_lifecyclestage_marketingqualifiedlead_date",
		EventName: "",
		Entity:    model.UserEntity,
	},
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "salesqualifiedlead",
				LogicalOp:        "AND",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "opportunity",
				LogicalOp:        "OR",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "customer",
				LogicalOp:        "OR",
			},
		},
		DateField: "$hubspot_contact_hs_lifecyclestage_salesqualifiedlead_date",
		EventName: "",
		Entity:    model.UserEntity,
	},
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "opportunity",
				LogicalOp:        "AND",
			},
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "customer",
				LogicalOp:        "OR",
			},
		},
		DateField: "$hubspot_contact_hs_lifecyclestage_opportunity_date",
		EventName: "",
		Entity:    model.UserEntity,
	},
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_contact_lifecyclestage",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "customer",
				LogicalOp:        "AND",
			},
		},
		DateField: "$hubspot_contact_hs_lifecyclestage_customer_date",
		EventName: "",
		Entity:    model.UserEntity,
	},
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters:               []model.KPIFilter{},
		DateField:             "$hubspot_deal_createdate",
		EventName:             "",
		Entity:                model.UserEntity,
	},
	{
		AggregateFunction:     model.SumAggregateFunction,
		AggregateProperty:     "$hubspot_deal_amount",
		AggregatePropertyType: "categorical",
		Filters:               []model.KPIFilter{},
		DateField:             "$hubspot_deal_createdate",
		EventName:             "",
		Entity:                model.UserEntity,
	},
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_deal_hs_is_closed_won",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "true",
				LogicalOp:        "AND",
			},
		},
		DateField: "$hubspot_deal_createdate",
		EventName: "",
		Entity:    model.UserEntity,
	},
	{
		AggregateFunction:     model.SumAggregateFunction,
		AggregateProperty:     "$hubspot_deal_amount",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_deal_hs_is_closed_won",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "true",
				LogicalOp:        "AND",
			},
		},
		DateField: "$hubspot_deal_createdate",
		EventName: "",
		Entity:    model.UserEntity,
	},
	{
		AggregateFunction:     model.UniqueAggregateFunction,
		AggregateProperty:     "",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_deal_hs_is_closed_won",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "true",
				LogicalOp:        "AND",
			},
		},
		DateField: "$hubspot_deal_closedate",
		EventName: "",
		Entity:    model.UserEntity,
	},
	{
		AggregateFunction:     model.SumAggregateFunction,
		AggregateProperty:     "$hubspot_deal_amount",
		AggregatePropertyType: "categorical",
		Filters: []model.KPIFilter{
			{
				ObjectType:       "",
				PropertyName:     "$hubspot_deal_hs_is_closed_won",
				PropertyDataType: "categorical",
				Entity:           model.UserEntity,
				Condition:        model.EqualsOpStr,
				Value:            "true",
				LogicalOp:        "AND",
			},
		},
		DateField: "$hubspot_deal_closedate",
		EventName: "",
		Entity:    model.UserEntity,
	},
}

var defaultHubspotDerivedKPITransformations = []model.KPIQueryGroup{
	{
		Class: model.QueryClassKPI,
		Queries: []model.KPIQuery{
			{
				Category:         model.ProfileCategory,
				DisplayCategory:  model.HubspotContactsDisplayCategory,
				Metrics:          []string{"HubSpot SQLs (Contact Create Date)"},
				Filters:          []model.KPIFilter{},
				GroupBy:          []model.KPIGroupBy{},
				GroupByTimestamp: "",
				Timezone:         "",
				Operator:         "",
				QueryType:        "",
				Name:             "a",
			},
			{
				Category:         model.ProfileCategory,
				DisplayCategory:  model.HubspotContactsDisplayCategory,
				Metrics:          []string{"HubSpot MQLs (Contact Create Date)"},
				Filters:          []model.KPIFilter{},
				GroupBy:          []model.KPIGroupBy{},
				GroupByTimestamp: "",
				Timezone:         "",
				Operator:         "",
				QueryType:        "",
				Name:             "b",
			},
		},
		GlobalFilters: []model.KPIFilter{},
		GlobalGroupBy: []model.KPIGroupBy{},
		Formula:       "a/b",
	},
	{
		Class: model.QueryClassKPI,
		Queries: []model.KPIQuery{
			{
				Category:         model.ProfileCategory,
				DisplayCategory:  model.HubspotContactsDisplayCategory,
				Metrics:          []string{"HubSpot Opps (Contact Create Date)"},
				Filters:          []model.KPIFilter{},
				GroupBy:          []model.KPIGroupBy{},
				GroupByTimestamp: "",
				Timezone:         "",
				Operator:         "",
				QueryType:        "",
				Name:             "a",
			},
			{
				Category:         model.ProfileCategory,
				DisplayCategory:  model.HubspotContactsDisplayCategory,
				Metrics:          []string{"HubSpot SQLs (Contact Create Date)"},
				Filters:          []model.KPIFilter{},
				GroupBy:          []model.KPIGroupBy{},
				GroupByTimestamp: "",
				Timezone:         "",
				Operator:         "",
				QueryType:        "",
				Name:             "b",
			},
		},
		GlobalFilters: []model.KPIFilter{},
		GlobalGroupBy: []model.KPIGroupBy{},
		Formula:       "a/b",
	},
	{
		Class: model.QueryClassKPI,
		Queries: []model.KPIQuery{
			{
				Category:         model.ProfileCategory,
				DisplayCategory:  model.HubspotContactsDisplayCategory,
				Metrics:          []string{"HubSpot Customers (Contact Create Date)"},
				Filters:          []model.KPIFilter{},
				GroupBy:          []model.KPIGroupBy{},
				GroupByTimestamp: "",
				Timezone:         "",
				Operator:         "",
				QueryType:        "",
				Name:             "a",
			},
			{
				Category:         model.ProfileCategory,
				DisplayCategory:  model.HubspotContactsDisplayCategory,
				Metrics:          []string{"HubSpot Opps (Contact Create Date)"},
				Filters:          []model.KPIFilter{},
				GroupBy:          []model.KPIGroupBy{},
				GroupByTimestamp: "",
				Timezone:         "",
				Operator:         "",
				QueryType:        "",
				Name:             "b",
			},
		},
		GlobalFilters: []model.KPIFilter{},
		GlobalGroupBy: []model.KPIGroupBy{},
		Formula:       "a/b",
	},
}

type BuildDefaultHubspotCustomKPI struct {
}

func (buildDefault BuildDefaultHubspotCustomKPI) Build(projectID int64) int {
	if !CheckIfDefaultHubspotDatasAreCorrect() {
		log.Warn("Failed because defaultDatas and transformations are of incorrect length.")
		return http.StatusInternalServerError
	}
	return buildForCustomKPI(projectID, defaultHubspotCustomKPIs, defaultHubspotCustomKPITransformations, defaultHubspotDerivedKPITransformations)
}

func CheckIfDefaultHubspotDatasAreCorrect() bool {
	return len(defaultHubspotCustomKPIs) == (len(defaultHubspotCustomKPITransformations) + len(defaultHubspotDerivedKPITransformations))
}
