export const PathUrls = {
  Dashboard: '/',
  ComponentsLib: '/components',
  Analyse: '/analyse/:query_type/:query_id',
  Analyse1: '/analyse/:query_type',
  Analyse2: '/analyse',
  Explain: '/explain',
  ExplainInsightsV2: '/explainV2/insights',
  ProfilePeople: '/profiles/people',
  ProfileAccounts: '/profiles/accounts',
  VisitorIdentificationReport: '/reports/visitor_report',
  PathAnalysis: '/path-analysis',
  ConfigureEvents: '/configure/events',
  ConfigureProperties: '/configure/properties',
  ConfigureContentGroups: '/configure/contentgroups',
  ConfigureTouchPoints: '/configure/touchpoints',
  ConfigureCustomKpi: '/configure/customkpi',
  ConfigureDataPoints: '/configure/explaindp',
  ConfigureAlerts: '/configure/alerts',
  SettingsGeneral: '/settings/general',
  SettingsUser: '/settings/user',
  SettingsAttribution: '/settings/attribution',
  SettingsSdk: '/settings/sdk',
  SettingsIntegration: '/settings/integration',
  SettingsSharing: '/settings/sharing',
  SettingsInsights: '/settings/insights'
};
