export const SET_TIMELINE_PAYLOAD = 'SET_TIMELINE_PAYLOAD';
export const SET_PROFILES_ACTIVE_SEGMENT = 'SET_PROFILES_ACTIVE_SEGMENT';
export const UPDATE_TIMELINE_PAYLOAD = 'UPDATE_TIMELINE_PAYLOAD';
export const SET_PROFILE_SEGMENT_MODAL = 'SET_PROFILE_SEGMENT_MODAL';
