FROM python:3.7-alpine

WORKDIR /hubspot
COPY sync.py .
RUN apk add --no-cache --virtual .build-deps gcc libc-dev libxslt-dev && \
    apk add --no-cache libxslt && \
    pip install --no-cache-dir lxml>=3.5.0 && \
    apk del .build-deps

ENTRYPOINT ["python", "sync.py"]