// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-11-06 00:39:58.695603 +0530 IST m=+1.498067692

package docs

import (
	"bytes"
	"encoding/json"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "Factors usage doc for golang api server.",
        "title": "Factors Backend Api",
        "contact": {},
        "license": {},
        "version": "1.0"
    },
    "host": "factors-dev.com:8080",
    "basePath": "/projects",
    "paths": {
        "/{project_id}/dashboard/{dashboard_id}/units/query/web_analytics": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DashboardUnit"
                ],
                "summary": "To fetch result for website analytics dashboard queries.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Dashboard ID",
                        "name": "dashboard_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Web analytics units",
                        "name": "unit",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/handler.DashboardUnitsWebAnalyticsQuery"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"result\": \"result\", \"cache\": \"true\", \"refreshed_at\": \"timestamp\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{project_id}/dashboards": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Fetches all dashboards for the given project id.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Found",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Dashboard"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Creates a new dashboard for the given input.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create new dashboard",
                        "name": "dashboard",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/handler.DashboardRequestPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Dashboard"
                        }
                    }
                }
            }
        },
        "/{project_id}/dashboards/{dashboard_id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Updates an existing dashboard.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Dashboard ID",
                        "name": "dashboard_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update dashboard",
                        "name": "unit",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.UpdatableDashboard"
                        }
                    }
                ],
                "responses": {
                    "202": {}
                }
            }
        },
        "/{project_id}/dashboards/{dashboard_id}/units": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DashboardUnit"
                ],
                "summary": "Fetches dashboard units for the given project and dashboard id.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Dashboard ID",
                        "name": "dashboard_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Found",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.DashboardUnit"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DashboardUnit"
                ],
                "summary": "Creates a new dashboard unit for the given input.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Dashboard ID",
                        "name": "dashboard_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create dashboard unit",
                        "name": "unit",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.DashboardUnitRequestPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.DashboardUnit"
                        }
                    }
                }
            }
        },
        "/{project_id}/dashboards/{dashboard_id}/units/{unit_id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DashboardUnit"
                ],
                "summary": "To update an existing dashboard unit.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Dashboard ID",
                        "name": "dashboard_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Dashboard Unit ID",
                        "name": "unit_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update dashboard unit",
                        "name": "unit",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.DashboardUnitRequestPayload"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "{\"message\": \"Successfully updated.\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DashboardUnit"
                ],
                "summary": "To delete an existing dashboard unit.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Dashboard ID",
                        "name": "dashboard_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Dashboard Unit ID",
                        "name": "unit_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "{\"message\": \"Successfully deleted.\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{project_id}/filters": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Filters"
                ],
                "summary": "Get the list of existing filters.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handler.API_FilterResponePayload"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Filters"
                ],
                "summary": "To create a new filter.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create filter",
                        "name": "filter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/handler.API_FilterRequestPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/handler.API_FilterResponePayload"
                        }
                    }
                }
            }
        },
        "/{project_id}/filters/{filter_id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Filters"
                ],
                "summary": "To update an existing filter.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Filter ID",
                        "name": "filter_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update filter",
                        "name": "filter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/handler.API_FilterRequestPayload"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/handler.API_FilterResponePayload"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Filters"
                ],
                "summary": "To delete an existing filter.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Filter ID",
                        "name": "filter_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/handler.API_FilterResponePayload"
                        }
                    }
                }
            }
        },
        "/{project_id}/queries": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SavedQuery"
                ],
                "summary": "To get list of all saved queries in project.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Found",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Queries"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SavedQuery"
                ],
                "summary": "To create a new saved query for given query.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create saved query",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/handler.SavedQueryRequestPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Queries"
                            }
                        }
                    }
                }
            }
        },
        "/{project_id}/queries/search": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SavedQuery"
                ],
                "summary": "To search on existing saved queries.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Found",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Queries"
                            }
                        }
                    }
                }
            }
        },
        "/{project_id}/queries/{query_id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SavedQuery"
                ],
                "summary": "To update an existing saved query.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Query ID",
                        "name": "query_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update saved query",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/handler.SavedQueryUpdatePayload"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "{\"message\": \"Successfully updated.\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SavedQuery"
                ],
                "summary": "To delete an existing saved query.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Query ID",
                        "name": "query_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "{\"message\": \"Successfully deleted.\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{project_id}/settings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ProjectSettings"
                ],
                "summary": "Retrieves the project settings for given project id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ProjectSetting"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.API_FilterRequestPayload": {
            "type": "object",
            "properties": {
                "expr": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "handler.API_FilterResponePayload": {
            "type": "object",
            "properties": {
                "deleted": {
                    "type": "boolean"
                },
                "expr": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "project_id": {
                    "type": "integer"
                }
            }
        },
        "handler.DashboardRequestPayload": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "handler.DashboardUnitWebAnalyticsCustomGroupQuery": {
            "type": "object",
            "properties": {
                "gbp": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "metrics": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "unit_id": {
                    "type": "integer"
                }
            }
        },
        "handler.DashboardUnitWebAnalyticsQueryName": {
            "type": "object",
            "properties": {
                "query_name": {
                    "type": "string"
                },
                "unit_id": {
                    "type": "integer"
                }
            }
        },
        "handler.DashboardUnitsWebAnalyticsQuery": {
            "type": "object",
            "properties": {
                "custom_group_units": {
                    "description": "CustomGroupUnits - Customize query with group by properties and metrics.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.DashboardUnitWebAnalyticsCustomGroupQuery"
                    }
                },
                "from": {
                    "type": "integer"
                },
                "to": {
                    "type": "integer"
                },
                "units": {
                    "description": "Units - Supports redundant metric keys with different unit_ids.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.DashboardUnitWebAnalyticsQueryName"
                    }
                }
            }
        },
        "handler.SavedQueryRequestPayload": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "handler.SavedQueryUpdatePayload": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string"
                }
            }
        },
        "model.Dashboard": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "description": "Composite primary key, id + project_id + agent_id.",
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "project_id": {
                    "description": "Foreign key dashboards(project_id) ref projects(id).",
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "units_position": {
                    "description": "map[string]map[uint64]int -\u003e map[unit_type]unit_id:unit_position",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.DashboardUnit": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "dashboard_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "description": "Composite primary key, id + project_id.",
                    "type": "integer"
                },
                "presentation": {
                    "type": "string"
                },
                "project_id": {
                    "description": "Foreign key dashboard_units(project_id) ref projects(id).",
                    "type": "integer"
                },
                "query": {
                    "description": "TODO (Anil) remove this field once we move to saved queries",
                    "type": "string"
                },
                "query_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.DashboardUnitRequestPayload": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "presentation": {
                    "type": "string"
                },
                "query": {
                    "type": "string"
                },
                "query_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.ProjectSetting": {
            "type": "object",
            "properties": {
                "archive_enabled": {
                    "description": "Archival related fields.",
                    "type": "boolean"
                },
                "auto_form_capture": {
                    "type": "boolean"
                },
                "auto_track": {
                    "description": "Using pointers to avoid update by default value.\nomit empty to avoid nil(filelds not updated) on resp json.",
                    "type": "boolean"
                },
                "bigquery_enabled": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "exclude_bot": {
                    "type": "boolean"
                },
                "int_adwords_customer_account_id": {
                    "type": "string"
                },
                "int_adwords_enabled_agent_uuid": {
                    "description": "Adwords integration settings.\nForeign key constraint int_adwords_enabled_agent_uuid -\u003e agents(uuid)\nTodo: Set int_adwords_enabled_agent_uuid, int_adwords_customer_account_id to NULL\nfor disabling adwords integration for the project.",
                    "type": "string"
                },
                "int_facebook_access_token": {
                    "type": "string"
                },
                "int_facebook_ad_account": {
                    "type": "string"
                },
                "int_facebook_agent_uuid": {
                    "type": "string"
                },
                "int_facebook_email": {
                    "description": "Facebook settings",
                    "type": "string"
                },
                "int_facebook_user_id": {
                    "type": "string"
                },
                "int_hubspot": {
                    "description": "Hubspot integration settings.",
                    "type": "boolean"
                },
                "int_hubspot_api_key": {
                    "type": "string"
                },
                "int_salesforce_enabled_agent_uuid": {
                    "description": "Salesforce settings",
                    "type": "string"
                },
                "int_segment": {
                    "description": "Segment integration settings.",
                    "type": "boolean"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.Queries": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "id": {
                    "description": "Composite primary key, id + project_id.",
                    "type": "integer"
                },
                "is_deleted": {
                    "type": "boolean"
                },
                "project_id": {
                    "description": "Foreign key queries(project_id) ref projects(id).",
                    "type": "integer"
                },
                "query": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.UpdatableDashboard": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "units_position": {
                    "type": "object"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{ Schemes: []string{}}

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface {}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
