apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: factors-staging-node-pool
  name: add-session-job
spec:
  schedule: "*/30 * * * *" # every 30 minutes
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: factors-staging-node-pool
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: factors-staging-node-pool
          containers:
          - name: add-session-job
            image: us.gcr.io/factors-staging/add-session-job:859291fb0-1542
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --db_host
            - $(DB_HOST)
            - --db_port
            - $(DB_PORT)
            - --db_name
            - $(POSTGRES_DB)
            - --db_user
            - $(POSTGRES_USER)
            - --redis_host
            - $(REDIS_HOST)
            - --redis_port
            - $(REDIS_PORT)
            - --db_pass
            - $(POSTGRES_PASSWORD)
            - --project_ids
            - "*"
            - --num_project_routines
            - $(ADD_SESSION_PROJECT_ROUTINES)
            - --num_user_routines
            - $(ADD_SESSION_USER_ROUTINES)
            - --num_project_routines
            - $(ADD_SESSION_PROJECT_ROUTINES)
            - --num_user_routines
            - $(ADD_SESSION_USER_ROUTINES)
            - --max_lookback_hours
            - $(ADD_SESSION_MAX_LOOKBACK_HOURS)
            - --start_timestamp
            - "0"
            - --end_timestamp
            - "0"
            - --redis_host_ps
            - $(PERSISTENT_REDIS_HOST)
            - --redis_port_ps
            - $(PERSISTENT_REDIS_PORT)
            - --sentry_dsn
            - $(SENTRY_DSN)
            - --gcp_project_id
            - $(GCP_PROJECT_ID)
            - --gcp_project_location
            - $(GCP_PROJECT_LOCATION)
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-memsql
            - configMapRef:
                name: config-redis
            - configMapRef:
                name: config-add-session-job
            - secretRef:
                name: secret-memsql
            - secretRef:
                name: secret-sentry
            - configMapRef:
                name: config-persistent-redis
          restartPolicy: OnFailure
