apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: adwords-sync-job
spec:
  schedule: "0 22 * * *" # In UTC
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: factors-staging-node-pool
          containers:
          - name: adwords-sync
            image: us.gcr.io/factors-staging/adwords-sync:v0.10-c259cba
            imagePullPolicy: IfNotPresent
            args:
            - --oauth_secret
            - $(GOOGLE_OAUTH_SECRET)
            - --developer_token
            - $(GOOGLE_ADWORDS_DEVELOPER_TOKEN)
            - --data_service_host
            - $(DATA_SERVICE_HOST_URL)
            envFrom:
            - configMapRef:
                name: config-adwordsserver
            - configMapRef:
                name: config-env
            - secretRef:
                name: secret-google
          restartPolicy: OnFailure