apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: factors-staging-node-pool
  name: archive-events-job
spec:
  schedule: "30 0 * * *" # In UTC
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: factors-staging-node-pool
          containers:
          - name: archive-events-job
            image: us.gcr.io/factors-staging/archive-events-job:v0.71_4a75f686
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --bucket_name
            - $(ARCHIVE_BUCKET_NAME)
            - --tmp_dir
            - /tmp
            - --db_host
            - $(DB_HOST)
            - --db_port
            - $(DB_PORT)
            - --db_name
            - $(POSTGRES_DB)
            - --db_user
            - $(POSTGRES_USER)
            - --db_pass
            - $(POSTGRES_PASSWORD)
            - --max_lookback_days
            - $(MAX_LOOKBACK_DAYS)
            - --all
            - $(ARCHIVE_ALL)
            - --sentry_dsn
            - $(SENTRY_DSN)
            - --gcp_project_id
            - $(GCP_PROJECT_ID)
            - --gcp_project_location
            - $(GCP_PROJECT_LOCATION)
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-bucket
            - configMapRef:
                name: config-postgres
            - configMapRef:
                name: config-archiveeventsjob
            - secretRef:
                name: secret-postgres
            - secretRef:
                name: secret-sentry
          restartPolicy: OnFailure
