apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: build-seq-job
spec:
  schedule: "0 15 * * *" # In UTC
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: factors-staging-node-pool
          containers:
          - name: build-seq-job
            image: us.gcr.io/factors-staging/build-seq-job:v0.5-beta_adc1743
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --etcd
            - $(ETCD)
            - --bucket_name
            - $(BUCKET_NAME)
            - --local_disk_tmp_dir
            - /tmp
            - --db_host
            - $(DB_HOST)
            - --db_port
            - $(DB_PORT)
            - --db_name
            - $(POSTGRES_DB)
            - --db_user
            - $(POSTGRES_USER)
            - --db_pass
            - $(POSTGRES_PASSWORD)
            envFrom:
            - configMapRef:
                name: config-etcd
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-bucket
            - configMapRef:
                name: config-postgres
            - secretRef:
                name: secret-postgres
          restartPolicy: OnFailure
