
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    nodePool: staging-containerd
  name: copy-project-data
spec:
  schedule: "* * * * *"
  suspend: true
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: staging-containerd
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: staging-containerd
          containers:
          - name: copy-project-data
            image: us.gcr.io/factors-staging/copy-project-data:v1-test
            imagePullPolicy: IfNotPresent
            args:
            -- REDIS_HOST
            - "10.0.0.67"
            -- REDIS_PORT
            - "6379"
            -- EXTERNAL_IP
            - "104.196.253.121"
            -- DB_USER_NAME
            - "root"
            -- DB_HOST
            - "104.196.253.121"
            -- DB_PASSWORD
            - "dbfacttors"
            -- PROJECT_ID
            - "35000000"
          restartPolicy: OnFailure

  