apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: factors-staging-node-pool
  name: enrich-smart-properties-job
spec:
  schedule: "0 05 * * *" # In UTC
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: factors-staging-node-pool
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: factors-staging-node-pool
          containers:
          - name: enrich-smart-properties-job
            image: us.gcr.io/factors-staging/enrich-smart-properties-job:v0.01
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --db_host
            - $(DB_HOST)
            - --db_port
            - $(DB_PORT)
            - --db_name
            - $(POSTGRES_DB)
            - --db_user
            - $(POSTGRES_USER)
            - --db_pass
            - $(POSTGRES_PASSWORD)
            - --project_ids
            - ""
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-postgres
            - secretRef:
                name: secret-postgres
          restartPolicy: OnFailure
