apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hubspot-enrich-job
spec:
  schedule: "0 21 * * *" # In UTC
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: factors-staging-node-pool
          containers:
          - name: hubspot-enrich-job
            image: us.gcr.io/factors-staging/hubspot-enrich-job:v0.01-e489059
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --db_host
            - $(DB_HOST)
            - --db_port
            - $(DB_PORT)
            - --db_name
            - $(POSTGRES_DB)
            - --db_user
            - $(POSTGRES_USER)
            - --db_pass
            - $(POSTGRES_PASSWORD)
            - --redis_host
            - $(REDIS_HOST)
            - --redis_port
            - $(REDIS_PORT)
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-postgres
            - secretRef:
                name: secret-postgres
            - configMapRef:
                name: config-redis
          restartPolicy: OnFailure