apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: factors-staging-node-pool
  name: ingest-staging-job
spec:
  schedule: "1 2 3 4 5" # Random one time schedule to avoid running periodically.
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: factors-staging-node-pool
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: factors-staging-node-pool
          containers:
          - name: ingest-staging-job
            image: us.gcr.io/factors-staging/ingest-staging-job:0.1
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --memsql_host
            - $(MEMSQL_HOST)
            - --memsql_port
            - $(MEMSQL_PORT)
            - --memsql_name
            - $(MEMSQL_DB)
            - --memsql_user
            - $(MEMSQL_HEAVY_USER)
            - --memsql_pass
            - $(MEMSQL_PASSWORD)
            - --memsql_cert
            - $(MEMSQL_CERTIFICATE)
            - --jobConfig
            - "attribution" 
            - --projectIdStaging
            - "141"
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-memsql
            - secretRef:
                name: secret-memsql
          restartPolicy: OnFailure