apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: factors-staging-node-pool
  name: journey-mining-job
spec:
  schedule: "1 2 3 4 5" # In UTC
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: factors-staging-node-pool
          containers:
          - name: journey-mining-job
            image: us.gcr.io/factors-staging/journey-mining-job:v0.71_4a75f686
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --bucket_name
            - $(ARCHIVE_BUCKET_NAME)
            - --tmp_dir
            - /tmp
            - --db_host
            - $(DB_HOST)
            - --db_port
            - $(DB_PORT)
            - --db_name
            - $(POSTGRES_DB)
            - --db_user
            - $(POSTGRES_USER)
            - --db_pass
            - $(POSTGRES_PASSWORD)
            - --project_id
            - "386"
            - --start_date
            - "2020-08-01"
            - --end_date
            - "2020-08-15"
            - --include_session
            - "true"
            - --session_property
            - "$campaign"
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-bucket
            - configMapRef:
                name: config-postgres
            - secretRef:
                name: secret-postgres
            - configMapRef:
                name: config-archiveeventsjob
          restartPolicy: OnFailure
