apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: factors-staging-node-pool
  name: linkedin-sync-job
spec:
  schedule: "0 19 * * *" # In UTC
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: factors-staging-node-pool
          containers:
          - name: linkedin-sync
            image: us.gcr.io/factors-staging/linkedin-sync-job:v0.01
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --data_service_host
            - $(DATA_SERVICE_MEMSQL_HOST_URL)
            - --client_id
            - $(LINKEDIN_CLIENT_ID)
            - --client_secret
            - $(LINKEDIN_CLIENT_SECRET)
            - --run_member_insights_only
            - "False"
            envFrom:
            - configMapRef:
                name: config-env
            - secretRef:
              name: secret-linkedin
          restartPolicy: OnFailure