apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: factors-staging-node-pool
  name: marketo-sync-job
spec:
  schedule: "1 2 3 4 5" # In UTC
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: factors-staging-node-pool
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: factors-staging-node-pool
          containers:
          - name: marketo-sync-job
            image: us.gcr.io/factors-staging/marketo-sync-job:V20220412-2
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --primary_datastore
            - memsql
            - --memsql_host
            - $(MEMSQL_HOST)
            - --memsql_port
            - $(MEMSQL_PORT)
            - --memsql_name
            - $(MEMSQL_DB)
            - --memsql_user
            - $(MEMSQL_USER)
            - --memsql_pass
            - $(MEMSQL_PASSWORD)
            - --memsql_cert
            - $(MEMSQL_CERTIFICATE)
            - --bigquery_project_id
            - $(BIGQUERY_PROJECT_ID)
            - --bigquery_credential_json
            - $(BIGQUERY_CREDENTIAL)
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-memsql
            - secretRef:
                name: secret-memsql
            - secretRef:
                name: secret-bigquery
          restartPolicy: OnFailure