apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: factors-staging-node-pool
  name: migrate-model-metadata-todb-job
spec:
  schedule: "1 2 3 4 5" #On Trigger
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: factors-staging-node-pool
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: factors-staging-node-pool
          containers:
          - name: migrate-model-metadata-todb-job
            image: us.gcr.io/factors-staging/migrate-model-metadata-todb-job:v0.1
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --db_host
            - $(DB_HOST)
            - --db_port
            - $(DB_PORT)
            - --db_name
            - $(POSTGRES_DB)
            - --db_user
            - $(POSTGRES_USER)
            - --db_pass
            - $(POSTGRES_PASSWORD)
            - --bucket_name_v2
            - $(BUCKET_NAME)
            - --metadata_version
            - "1621233980"
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-postgres
            - secretRef:
                name: secret-postgres
            - secretRef:
                name: config-bucket
          restartPolicy: OnFailure
