apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: factors-staging-node-pool
  name: pg-backup
spec:
  schedule: "10 */2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pg-backup-job
            image: us.gcr.io/factors-staging/pg-backup:v4-beta-459bd0e
            imagePullPolicy: IfNotPresent
            envFrom:
            - secretRef:
                name: secret-memsql
            - configMapRef:
                name: config-memsql
          restartPolicy: Never