apiVersion: batch/v1
kind: Job
metadata:
  labels:
    nodePool: staging-containerd
  name: product-analytics-job
spec:
  backoffLimit: 1000  
  template:
    metadata:
      labels:
        layer: jobs
        nodePool: staging-containerd
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: staging-containerd
      containers:
      - name: product-analytics-job
        image: us.gcr.io/factors-staging/product-analytics-job:0.2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "100M"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: OnFailure
