apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: factors-staging-node-pool
  name: segment-marker-job
spec:
  schedule: "0 12 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: factors-staging-node-pool
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: factors-staging-node-pool
          containers:
            - name: segment-marker-job
              image: us.gcr.io/factors-staging/segment-marker-job:v0.01
              imagePullPolicy: IfNotPresent
              args:
                - --env
                - $(ENV)
                - --memsql_host
                - $(MEMSQL_HOST)
                - --memsql_port
                - $(MEMSQL_PORT)
                - --memsql_name
                - $(MEMSQL_DB)
                - --memsql_user
                - $(MEMSQL_HEAVY_USER)
                - --memsql_pass
                - $(MEMSQL_PASSWORD)
                - --memsql_cert
                - $(MEMSQL_CERTIFICATE)
                - --project_ids
                - "*"
              envFrom:
                - configMapRef:
                    name: config-env
                - configMapRef:
                    name: config-memsql
                - secretRef:
                    name: secret-memsql
          restartPolicy: OnFailure
