apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: factors-staging-node-pool
  name: sixsignal-report-job
spec:
  schedule: "1 2 3 4 5" # In UTC
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: factors-staging-node-pool
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: factors-staging-node-pool
          containers:
          - name: sixsignal-report-job
            image: us.gcr.io/factors-staging/sixsignal-report-job:1.0
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --bucket_name
            - $(BUCKET_NAME)
            - --local_disk_tmp_dir
            - /tmp
            - --memsql_host
            - $(MEMSQL_HOST)
            - --memsql_port
            - $(MEMSQL_PORT)
            - --memsql_name
            - $(MEMSQL_DB)
            - --memsql_user
            - $(MEMSQL_HEAVY_USER)
            - --memsql_pass
            - $(MEMSQL_PASSWORD)
            - --memsql_cert
            - $(MEMSQL_CERTIFICATE)
            - --project_ids
            - "399"
            - --weekly_enabled
            - --lookback
            - "13"
            - --k
            - "100"
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-bucket
            - configMapRef:
                name: config-memsql
            - secretRef:
                name: secret-memsql
          restartPolicy: OnFailure