apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    nodePool: staging-containerd
  name: slack-users-sync-job
spec:
  schedule: "1 2 3 4 5"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: staging-containerd
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: staging-containerd
          containers:
            - name: slack-users-sync-job
              image: us.gcr.io/factors-staging/slack-users-sync-job:v1
              imagePullPolicy: IfNotPresent
              args:
                - --env
                - $(ENV)
                - --memsql_host
                - $(MEMSQL_HOST)
                - --memsql_port
                - $(MEMSQL_PORT)
                - --memsql_name
                - $(MEMSQL_DB)
                - --memsql_user
                - $(MEMSQL_USER)
                - --memsql_pass
                - $(MEMSQL_PASSWORD)
                - --memsql_cert
                - $(MEMSQL_CERTIFICATE)
                - --primary_datastore
                - "memsql"
              envFrom:
                - configMapRef:
                    name: config-env
                - configMapRef:
                    name: config-memsql
                - secretRef:
                    name: secret-memsql
                - secretRef:
                    name: secret-sentry
          restartPolicy: OnFailure
