apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: memsql-ssd
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  type: pd-ssd
  fstype: ext4
  replication-type: none