apiVersion: v1
kind: ConfigMap
metadata:
  name: config-persistent-redis
  labels:
    env: production
    project: factors-production
data:
  PERSISTENT_REDIS_HOST: "localhost"
  PERSISTENT_REDIS_PORT: "8379"