FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/pull_events $GOPATH/src/factors/scripts/memsql/pull_events/pull_events.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/pull_events /go/bin/pull_events
ENTRYPOINT ["/go/bin/pull_events"]