FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/copy_user_properties $GOPATH/src/factors/migrations/scripts/run_copy_user_properties/run_copy_user_properties.go

# Create stripped down version without go and source code
FROM alpine:3.7
ENV GOLANG_PROTOBUF_REGISTRATION_CONFLICT=ignore
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/copy_user_properties /go/bin/copy_user_properties
ENTRYPOINT ["/go/bin/copy_user_properties"]
