FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/adhocarchiveeventsjob $GOPATH/src/factors/scripts/run_adhoc_archive_events/run_adhoc_archive_events.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/adhocarchiveeventsjob /go/bin/adhocarchiveeventsjob
ENTRYPOINT ["/go/bin/adhocarchiveeventsjob"]
