FROM golang:1.14-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/add_session $GOPATH/src/factors/scripts/run_add_session/run_add_session.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/add_session /go/bin/add_session
ENTRYPOINT ["/go/bin/add_session"]
