FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/run_cache_cleanup_filter_lists $GOPATH/src/factors/scripts/run_cache_cleanup_filter_lists/run_cache_cleanup_filter_lists.go

# Create stripped down version without go and source code
FROM alpine:3.7
ENV GOLANG_PROTOBUF_REGISTRATION_CONFLICT=ignore
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
ADD https://github.com/golang/go/raw/master/lib/time/zoneinfo.zip /usr/local/go/lib/time/zoneinfo.zip
COPY --from=builder /go/bin/run_cache_cleanup_filter_lists /go/bin/run_cache_cleanup_filter_lists
ENTRYPOINT ["/go/bin/run_cache_cleanup_filter_lists"]