FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/pattern-app $GOPATH/src/factors/pattern_server/cmd/pattern-app.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/pattern-app /go/bin/pattern-app
ENTRYPOINT [ "/go/bin/pattern-app"]
EXPOSE 8100