FROM golang:1.11-alpine

RUN apk update && apk add curl && apk add postgresql-client && echo "http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && apk add etcd-ctl &&  apk add ca-certificates && rm -rf /var/cache/apk/*
ENTRYPOINT [ "/bin/sh"]
