FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/run_fix_memsql_hubspot_sync_fields $GOPATH/src/factors/migrations/scripts/run_fix_memsql_hubspot_sync_fields/run_fix_memsql_hubspot_sync_fields.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/run_fix_memsql_hubspot_sync_fields /go/bin/run_fix_memsql_hubspot_sync_fields
ENTRYPOINT ["/go/bin/run_fix_memsql_hubspot_sync_fields"]