FROM golang:1.20-buster
WORKDIR /go/src/factors
ADD /factors .

# Fixes: time.LoadLocation(ZONE_NAME) error, zoneinfo.zip no such file or directory.
ADD https://github.com/golang/go/raw/master/lib/time/zoneinfo.zip /usr/local/go/lib/time/zoneinfo.zip

ENV GOPATH=/go
RUN apt-get update -y && apt-get install -y ca-certificates && go build -o /go/bin/beamaddsession /go/src/factors/scripts/run_beam_add_session/run_beam_add_session.go

ENTRYPOINT ["/go/bin/beamaddsession"]
