FROM golang:1.11-alpine AS builder

ENV GOPATH /go
WORKDIR /go/src/factors
ADD /factors .
RUN go build -o /go/src/factors/backend/bin/builddb scripts/run_db_create.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/src/factors/backend/bin/builddb /go/src/factors/backend/bin/builddb
ENTRYPOINT ["/go/src/factors/backend/bin/builddb", "--db_host", "postgres"]