FROM golang:1.14-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/delete_older_clickable_elements $GOPATH/src/factors/scripts/run_delete_older_clickable_elements/run_delete_older_clickable_elements.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
ADD https://github.com/golang/go/raw/master/lib/time/zoneinfo.zip /usr/local/go/lib/time/zoneinfo.zip
COPY --from=builder /go/bin/delete_older_clickable_elements /go/bin/delete_older_clickable_elements
ENTRYPOINT ["/go/bin/delete_older_clickable_elements"]
