FROM golang:1.14-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/dashboarddbjob $GOPATH/src/factors/scripts/run_db_dashboard_queries/run_db_dashboard_queries.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*

# Fixes: time.LoadLocation(ZONE_NAME) error, zoneinfo.zip no such file or directory.
ADD https://github.com/golang/go/raw/master/lib/time/zoneinfo.zip /usr/local/go/lib/time/zoneinfo.zip

COPY --from=builder /go/bin/dashboarddbjob /go/bin/dashboarddbjob
ENTRYPOINT ["/go/bin/dashboarddbjob"]
