FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/enrichsmartpropertiesjob $GOPATH/src/factors/scripts/run_enrich_smart_properties/run_enrich_smart_properties.go

# Create stripped down version without go and source code
FROM alpine:3.7
ENV GOLANG_PROTOBUF_REGISTRATION_CONFLICT=ignore
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/enrichsmartpropertiesjob /go/bin/enrichsmartpropertiesjob
ENTRYPOINT ["/go/bin/enrichsmartpropertiesjob"]
