FROM golang:1.14-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/ingest_test_data $GOPATH/src/factors/scripts/run_ingest_test_data/run_ingest_test_data.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/ingest_test_data /go/bin/ingest_test_data
ENTRYPOINT ["/go/bin/ingest_test_data"]