FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/replicator $GOPATH/src/factors/scripts/memsql/replicator/replicate.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/replicator /go/bin/replicator
ENTRYPOINT ["/go/bin/replicator"]