FROM golang:1.11-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/build_reports $GOPATH/src/factors/scripts/run_create_reports.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/build_reports /go/bin/build_reports
ENTRYPOINT ["/go/bin/build_reports"]