FROM golang:1.14-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/salesforceenrichjob $GOPATH/src/factors/scripts/run_salesforce_enrich/run_salesforce_enrich.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/salesforceenrichjob /go/bin/salesforceenrichjob
ENTRYPOINT ["/go/bin/salesforceenrichjob"]
