FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/run_free_plan_migration $GOPATH/src/factors/scripts/adhoc/run_free_plan_migration/run_free_plan_migration.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
ADD https://github.com/golang/go/raw/master/lib/time/zoneinfo.zip /usr/local/go/lib/time/zoneinfo.zip
COPY --from=builder /go/bin/run_free_plan_migration /go/bin/run_free_plan_migration
ENTRYPOINT ["/go/bin/run_free_plan_migration"]