FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/fill_user_properties $GOPATH/src/factors/scripts/memsql/fill_user_properties/fill_user_properties.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/fill_user_properties /go/bin/fill_user_properties
ENTRYPOINT ["/go/bin/fill_user_properties"]