FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/queries_id_text_patch $GOPATH/src/factors/scripts/run_queries_id_text_patch/insert_id_text_queries.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/queries_id_text_patch /go/bin/queries_id_text_patch
ENTRYPOINT ["/go/bin/queries_id_text_patch"]