FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/cleanup_eventuser_cache $GOPATH/src/factors/scripts/run_cleanup_eventuser_cache/run_cleanup_eventuser_cache.go

# Create stripped down version without go and source code
FROM alpine:3.7
ENV GOLANG_PROTOBUF_REGISTRATION_CONFLICT=ignore
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/cleanup_eventuser_cache /go/bin/cleanup_eventuser_cache
ENTRYPOINT ["/go/bin/cleanup_eventuser_cache"]
