FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/rollup_sortedset_cache $GOPATH/src/factors/scripts/run_rollup_sortedset_cache/run_rollup_sortedset_cache.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
# Fixes: time.LoadLocation(ZONE_NAME) error, zoneinfo.zip no such file or directory.
ADD https://github.com/golang/go/raw/master/lib/time/zoneinfo.zip /usr/local/go/lib/time/zoneinfo.zip
COPY --from=builder /go/bin/rollup_sortedset_cache /go/bin/rollup_sortedset_cache
ENTRYPOINT ["/go/bin/rollup_sortedset_cache"]
