FROM ubuntu:latest

WORKDIR /root

RUN apt-get update 
RUN apt-get install mariadb-client -y
RUN apt-get install redis -y 

COPY copy_project_data.sh /root/copy_project_data.sh

RUN chmod +x /root/copy_project_data.sh

ENTRYPOINT ["/root/copy_project_data.sh"]
