FROM golang:1.14-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/run_compute_and_send_alerts $GOPATH/src/factors/scripts/run_compute_and_send_alerts/run_compute_and_send_alerts.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/run_compute_and_send_alerts /go/bin/run_compute_and_send_alerts
ENTRYPOINT ["/go/bin/run_compute_and_send_alerts"]