FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/yourstory_add_properties $GOPATH/src/factors/scripts/custom/yourstory/run_add_missing_event_properties.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
# Fixes: time.LoadLocation(ZONE_NAME) error, zoneinfo.zip no such file or directory.
ADD https://github.com/golang/go/raw/master/lib/time/zoneinfo.zip /usr/local/go/lib/time/zoneinfo.zip

COPY --from=builder /go/bin/yourstory_add_properties /go/bin/yourstory_add_properties
ENTRYPOINT ["/go/bin/yourstory_add_properties"]
