FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/delete_dangling_sessions $GOPATH/src/factors/scripts/run_delete_dangling_sessions/run_delete_dangling_sessions.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/delete_dangling_sessions /go/bin/delete_dangling_sessions
ENTRYPOINT ["/go/bin/delete_dangling_sessions"]