FROM golang:1.14-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/onboardtobigqueryjob $GOPATH/src/factors/migrations/scripts/run_onboard_to_bigquery.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/onboardtobigqueryjob /go/bin/onboardtobigqueryjob
ENTRYPOINT ["/go/bin/onboardtobigqueryjob"]
