FROM ubuntu:latest

WORKDIR /root

RUN apt-get update \
    && apt-get install -y \
        redis-tools \
        mysql-client

COPY redis_scan_keys.sh /root/redis_scan_keys.sh

RUN chmod +x /root/redis_scan_keys.sh

ENTRYPOINT ["/root/redis_scan_keys.sh"]
