FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/ $GOPATH/src/factors/scripts/adhoc/country_name_to_isoCode_migration/country_name_to_isoCode_migration.go
# Create stripped down version without go and source code
FROM alpine:3.7
ENV GOLANG_PROTOBUF_REGISTRATION_CONFLICT=ignore
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
ADD https://github.com/golang/go/raw/master/lib/time/zoneinfo.zip /usr/local/go/lib/time/zoneinfo.zip
COPY --from=builder /go/bin/country_name_to_isoCode_migration /go/bin/country_name_to_isoCode_migration
ENTRYPOINT ["/go/bin/country_name_to_isoCode_migration"]
