FROM golang:1.14-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/hubspotenrichjob $GOPATH/src/factors/scripts/run_hubspot_enrich/run_hubspot_enrich.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/hubspotenrichjob /go/bin/hubspotenrichjob
ENTRYPOINT ["/go/bin/hubspotenrichjob"]
