FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/precompile_queries $GOPATH/src/factors/scripts/run_precompile_queries/run_precompile_queries.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/precompile_queries /go/bin/precompile_queries
ENTRYPOINT ["/go/bin/precompile_queries"]