FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/ $GOPATH/src/factors/scripts/channels_v1_to_kpi_query_migration/channels_v1_to_kpi_query_migration.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
ADD https://github.com/golang/go/raw/master/lib/time/zoneinfo.zip /usr/local/go/lib/time/zoneinfo.zip
COPY --from=builder /go/bin/channels_v1_to_kpi_query_migration /go/bin/channels_v1_to_kpi_query_migration
ENTRYPOINT ["/go/bin/channels_v1_to_kpi_query_migration"]
