FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/linkedinfrequencycapping $GOPATH/src/factors/scripts/run_linkedin_frequency_capping.go/run_linkedin_frequency_capping.go

# Create stripped down version without go and source code
FROM alpine:3.7
ENV GOLANG_PROTOBUF_REGISTRATION_CONFLICT=ignore
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
ADD https://github.com/golang/go/raw/master/lib/time/zoneinfo.zip /usr/local/go/lib/time/zoneinfo.zip
COPY --from=builder /go/bin/linkedinfrequencycapping /go/bin/linkedinfrequencycapping
ENTRYPOINT ["/go/bin/linkedinfrequencycapping"]
