FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/sixsignaltoclearbitmigrationjob $GOPATH/src/factors/scripts/adhoc/run_six_signal_to_clearbit_migration_script/run_six_signal_to_clearbit_migration.go

# Create stripped down version without go and source code
FROM alpine:3.7
ENV GOLANG_PROTOBUF_REGISTRATION_CONFLICT=ignore
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
# Fixes: time.LoadLocation(ZONE_NAME) error, zoneinfo.zip no such file or directory.
ADD https://github.com/golang/go/raw/master/lib/time/zoneinfo.zip /usr/local/go/lib/time/zoneinfo.zip

COPY --from=builder /go/bin/sixsignaltoclearbitmigrationjob /go/bin/sixsignaltoclearbitmigrationjob
ENTRYPOINT ["/go/bin/sixsignaltoclearbitmigrationjob"]