FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/predictpulleventsjob $GOPATH/src/factors/scripts/run_predict_pull_events/run_predict_pull_events.go

# Create stripped down version without go and source code
FROM alpine:3.7
ENV GOLANG_PROTOBUF_REGISTRATION_CONFLICT=ignore
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
ADD https://github.com/golang/go/raw/master/lib/time/zoneinfo.zip /usr/local/go/lib/time/zoneinfo.zip
COPY --from=builder /go/bin/predictpulleventsjob /go/bin/predictpulleventsjob
ENTRYPOINT ["/go/bin/predictpulleventsjob"]
