FROM golang:1.14-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/adwords_migration_job $GOPATH/src/factors/migrations/scripts/fill_campaign_id_ad_group_id_in_adwords_documents.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/adwords_migration_job /go/bin/adwords_migration_job
ENTRYPOINT ["/go/bin/adwords_migration_job"]
