FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/analyze $GOPATH/src/factors/scripts/run_analyze/run_analyze.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/analyze /go/bin/analyze
ENTRYPOINT ["/go/bin/analyze"]