FROM golang:1.14-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/weeklyinsightsjob $GOPATH/src/factors/scripts/run_delta_insights/run_delta_insights.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/weeklyinsightsjob /go/bin/weeklyinsightsjob
ENTRYPOINT ["/go/bin/weeklyinsightsjob"]