FROM golang:1.14-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/ingestleadgenjob $GOPATH/src/factors/scripts/run_ingest_leadgen_data/run_ingest_leadgen_data.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/ingestleadgenjob /go/bin/ingestleadgenjob
ENTRYPOINT ["/go/bin/ingestleadgenjob"]
