FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/createlinkedingroupuser $GOPATH/src/factors/scripts/run_create_linkedin_group_user/run_create_linkedin_group_user.go

# Create stripped down version without go and source code
FROM alpine:3.7
ENV GOLANG_PROTOBUF_REGISTRATION_CONFLICT=ignore
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
ADD https://github.com/golang/go/raw/master/lib/time/zoneinfo.zip /usr/local/go/lib/time/zoneinfo.zip
COPY --from=builder /go/bin/createlinkedingroupuser /go/bin/createlinkedingroupuser
ENTRYPOINT ["/go/bin/createlinkedingroupuser"]
