FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/segmentmarkerjob $GOPATH/src/factors/scripts/run_segment_marker/run_segment_marker.go


# Create stripped down version without go and source code
FROM alpine:3.7
ENV GOLANG_PROTOBUF_REGISTRATION_CONFLICT=ignore
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/segmentmarkerjob /go/bin/segmentmarkerjob
ENTRYPOINT ["/go/bin/segmentmarkerjob"]
