FROM golang:1.11-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/app $GOPATH/src/factors/app/app.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/app /go/bin/app
ENTRYPOINT [ "/go/bin/app"]
EXPOSE 8080