FROM golang:1.14-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/numericalbucketing $GOPATH/src/factors/scripts/run_numerical_bucketing/run_numerical_bucketing.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/numericalbucketing /go/bin/numericalbucketing
ENTRYPOINT ["/go/bin/numericalbucketing"]