FROM golang:1.20.3-alpine AS builder

WORKDIR /go/src/factors
ADD /factors .
RUN go build -o $GOPATH/bin/mergeuserpropertiesjob $GOPATH/src/factors/migrations/scripts/run_merge_user_properties.go

# Create stripped down version without go and source code
FROM alpine:3.7
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/mergeuserpropertiesjob /go/bin/mergeuserpropertiesjob
ENTRYPOINT ["/go/bin/mergeuserpropertiesjob"]
