apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: "2022-07-01T09:06:08Z"
  generation: 391
  labels:
    nodePool: adhoc-batch-pool
  managedFields:
  - apiVersion: batch/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:jobTemplate:
          f:spec:
            f:template:
              f:spec:
                f:securityContext: {}
    manager: kubectl-create
    operation: Update
    time: "2022-03-14T12:02:55Z"
  - apiVersion: batch/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels: {}
      f:spec:
        f:concurrencyPolicy: {}
        f:failedJobsHistoryLimit: {}
        f:jobTemplate:
          f:spec:
            f:template:
              f:metadata:
                f:labels:
                  .: {}
                  f:layer: {}
              f:spec:
                f:containers:
                  k:{"name":"acc-scoring-job"}:
                    .: {}
                    f:imagePullPolicy: {}
                    f:name: {}
                    f:resources:
                      .: {}
                      f:requests: {}
                    f:terminationMessagePath: {}
                    f:terminationMessagePolicy: {}
                f:dnsPolicy: {}
                f:restartPolicy: {}
                f:schedulerName: {}
                f:securityContext: {}
                f:terminationGracePeriodSeconds: {}
        f:schedule: {}
        f:successfulJobsHistoryLimit: {}
    manager: kubectl-create
    operation: Update
    time: "2022-07-01T09:06:08Z"
  - apiVersion: batch/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:lastSuccessfulTime: {}
    manager: kube-controller-manager
    operation: Update
    subresource: status
    time: "2022-08-08T07:30:24Z"
  - apiVersion: batch/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:nodePool: {}
      f:spec:
        f:jobTemplate:
          f:spec:
            f:template:
              f:metadata:
                f:labels:
                  f:nodePool: {}
              f:spec:
                f:containers:
                  k:{"name":"acc-scoring-job"}:
                    f:envFrom: {}
                    f:resources:
                      f:requests:
                        f:memory: {}
                f:nodeSelector: {}
        f:suspend: {}
    manager: GoogleCloudConsole
    operation: Update
    time: "2022-10-03T13:34:34Z"
  - apiVersion: batch/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:jobTemplate:
          f:spec:
            f:template:
              f:spec:
                f:containers:
                  k:{"name":"acc-scoring-job"}:
                    f:args: {}
                    f:image: {}
    manager: GoogleCloudConsole
    operation: Update
    time: "2022-11-24T09:56:37Z"
  name: acc-scoring-job
  namespace: default
  resourceVersion: "774952942"
  uid: 1d33fd8e-db2f-4601-b57d-91e70f691be7
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            layer: jobs
            nodePool: adhoc-batch-pool
        spec:
          containers:
          - args:
            - --no_use_public_ips
            - --env
            - $(ENV)
            - --bucket_name
            - $(BUCKET_NAME)
            - --local_disk_tmp_dir
            - /tmp
            - --archive_bucket_name
            - factors-production-archival
            - --model_bucket_name
            - factors-production-models
            - --project_ids
            - "2"
            - --day_time_stamp
            - "1677609000"
            - --lookback
            - "100"
            - --etcd
            - $(ETCD)
            - --num_beam_workers
            - "1000"
            - --runner
            - $(BEAM_RUNNER)
            - --project
            - $(BEAM_PROJECT)
            - --region
            - $(BEAM_REGION)
            - --zone
            - $(BEAM_ZONE)
            - --temp_location
            - $(BEAM_TEMP_LOCATION)
            - --staging_location
            - $(BEAM_STAGIN_LOCATION)
            - --worker_harness_container_image
            - $(BEAM_WORKER_HARNESS_IMAGE)
            - --subnetwork
            - $(BEAM_SUBNETWORK)
            - --worker_machine_type
            - n2-highmem-2
            - --num_workers
            - "20"
            - --max_num_workers
            - "20"
            - --primary_datastore
            - memsql
            - --memsql_host
            - $(MEMSQL_HOST)
            - --memsql_port
            - $(MEMSQL_PORT)
            - --memsql_name
            - $(MEMSQL_DB)
            - --memsql_user
            - $(MEMSQL_USER)
            - --memsql_pass
            - $(MEMSQL_PASSWORD)
            - --memsql_cert
            - $(MEMSQL_CERTIFICATE)
            - --redis_host
            - $(REDIS_HOST)
            - --redis_port
            - $(REDIS_PORT)
            - --redis_host_ps
            - $(PERSISTENT_REDIS_HOST)
            - --redis_port_ps
            - $(PERSISTENT_REDIS_PORT)
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-bucket
            - configMapRef:
                name: config-beamondataflow
            - configMapRef:
                name: config-etcd
            - configMapRef:
                name: config-persistent-redis
            - configMapRef:
                name: config-memsql
            - configMapRef:
                name: config-redis
            - secretRef:
                name: secret-memsql
            image: us.gcr.io/factors-production/acc-scoring-job:vtest1
            imagePullPolicy: IfNotPresent
            name: acc-scoring-job
            resources:
              requests:
                memory: 8G
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          nodeSelector:
            cloud.google.com/gke-nodepool: adhoc-batch-pool
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 1 2 3 4 5
  successfulJobsHistoryLimit: 5
  suspend: true
status:
  lastSuccessfulTime: "2022-11-29T00:38:20Z"