apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: persistent-pool-dataflow
  name: add-session-beam-job
spec:
  schedule: "*/30 * * * *" # every 30 minutes
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: persistent-pool-dataflow
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: persistent-pool-dataflow
          containers:
          - name: add-session-beam-job
            image: us.gcr.io/factors-production/add-session-beam-job:v1.01-a00eb51
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --db_host
            - $(DB_HOST)
            - --db_port
            - $(DB_PORT)
            - --db_name
            - $(POSTGRES_DB)
            - --db_user
            - $(POSTGRES_USER)
            - --db_pass
            - $(POSTGRES_PASSWORD)
            - --redis_host
            - $(REDIS_HOST)
            - --redis_port
            - $(REDIS_PORT)
            - --project_ids
            - "*"
            - --runner
            - $(BEAM_RUNNER)
            - --project
            - $(BEAM_PROJECT)
            - --region
            - $(BEAM_REGION)
            - --zone
            - $(BEAM_ZONE)
            - --temp_location
            - $(BEAM_TEMP_LOCATION)
            - --staging_location
            - $(BEAM_STAGIN_LOCATION)
            - --worker_harness_container_image
            - $(BEAM_WORKER_HARNESS_IMAGE)
            - --subnetwork
            - $(BEAM_SUBNETWORK)
            - --max_lookback_hours
            - $(ADD_SESSION_MAX_LOOKBACK_HOURS)
            - --start_timestamp
            - "0"
            - --end_timestamp
            - "0"
            - --redis_host_ps
            - $(PERSISTENT_REDIS_HOST)
            - --redis_port_ps
            - $(PERSISTENT_REDIS_PORT)
            - --sentry_dsn
            - $(SENTRY_DSN)
            - --gcp_project_id
            - $(GCP_PROJECT_ID)
            - --gcp_project_location
            - $(GCP_PROJECT_LOCATION)
            - --max_num_workers
            - "20"
            - --num_workers
            - "4"
            - --worker_machine_type
            - n2-highmem-2
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-postgres
            - configMapRef:
                name: config-redis
            - configMapRef:
                name: config-add-session-job
            - configMapRef:
                name: config-beamondataflow
            - secretRef:
                name: secret-postgres
            - secretRef:
                name: secret-sentry
            - configMapRef:
                name: config-persistent-redis
          restartPolicy: OnFailure
