apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: shared-persistent-pool
  name: adhoc-archive-events-job
spec:
  schedule: "1 2 3 4 5" # In UTC. Random time to avoid running periodically.
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: shared-persistent-pool
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: shared-persistent-pool
          containers:
          - name: adhoc-archive-events-job
            image: us.gcr.io/factors-production/adhoc-archive-events-job:v0.71_4a75f686
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --bucket_name
            - $(ARCHIVE_BUCKET_NAME)
            - --tmp_dir
            - /tmp
            - --memsql_host
            - $(MEMSQL_HOST)
            - --memsql_port
            - $(MEMSQL_PORT)
            - --memsql_name
            - $(MEMSQL_DB)
            - --memsql_user
            - $(MEMSQL_HEAVY_USER)
            - --memsql_pass
            - $(MEMSQL_PASSWORD)
            - --memsql_cert
            - $(MEMSQL_CERTIFICATE)
            - --project_id
            - ""
            - --num_routines
            - "2"
            - --start_date
            - ""
            - --end_date
            - ""
            - --sentry_dsn
            - $(SENTRY_DSN)
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-memsql
            - configMapRef:
                name: config-archiveeventsjob
            - secretRef:
                name: secret-memsql
            - secretRef:
                name: secret-sentry
          restartPolicy: OnFailure
