apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    nodePool: shared-persistent-pool2
  name: backfill-crm-deals-domain
spec:
  schedule: "0 20 * * *" # In UTC
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: shared-persistent-pool2
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: shared-persistent-pool2
          containers:
          - name: backfill-crm-deals-domain
            image: us.gcr.io/factors-production/backfill-crm-deals-domain:0.1
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --memsql_host
            - $(MEMSQL_PSC_HOST)
            - --memsql_is_psc_host
            - $(MEMSQL_IS_PSC_HOST)
            - --memsql_port
            - $(MEMSQL_PORT)
            - --memsql_name
            - $(MEMSQL_DB)
            - --memsql_user
            - $(MEMSQL_HEAVY_USER)
            - --memsql_pass
            - $(MEMSQL_PASSWORD)
            - --memsql_cert
            - $(MEMSQL_CERTIFICATE)
            - --redis_host
            - $(REDIS_HOST)
            - --redis_port
            - $(REDIS_PORT)
            - --redis_host_ps
            - $(PERSISTENT_REDIS_HOST)
            - --redis_port_ps
            - $(PERSISTENT_REDIS_PORT)
            - --sentry_dsn
            - $(SENTRY_DSN)
            - --project_ids
            - ""
            - --crm_source
            - ""
            - --start_time
            - ""
            - --end_time
            - ""
            envFrom:
            - configMapRef:
                name: config-redis
            - configMapRef:
                name: config-persistent-redis
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-memsql
            - secretRef:
                name: secret-memsql
            - secretRef:
                name: secret-sentry
          restartPolicy: OnFailure
