apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: persistent-pool-standard
  name: bigquery-upload-job
spec:
  schedule: "30 03 * * *" # In UTC
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: persistent-pool-standard
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: persistent-pool-standard
          containers:
          - name: bigquery-upload-job
            image: us.gcr.io/factors-production/bigquery-upload-job:v0.71_4a75f686
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --bucket_name
            - $(ARCHIVE_BUCKET_NAME)
            - --db_host
            - $(DB_HOST)
            - --db_port
            - $(DB_PORT)
            - --db_name
            - $(POSTGRES_DB)
            - --db_user
            - $(POSTGRES_USER)
            - --db_pass
            - $(POSTGRES_PASSWORD)
            - --all
            - $(UPLOAD_ALL)
            - --sentry_dsn
            - $(SENTRY_DSN)
            - --gcp_project_id
            - $(GCP_PROJECT_ID)
            - --gcp_project_location
            - $(GCP_PROJECT_LOCATION)
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-bucket
            - configMapRef:
                name: config-postgres
            - configMapRef:
                name: config-bigqueryuploadjob
            - secretRef:
                name: secret-postgres
            - secretRef:
                name: secret-sentry
          restartPolicy: OnFailure
