apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: persistent-pool-dataflow-build-seq
  name: build-seq-job
spec:
  schedule: "0 15 * * *" # In UTC
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: persistent-pool-dataflow-build-seq
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: persistent-pool-dataflow-build-seq
          containers:
          - name: build-seq-job
            image: us.gcr.io/factors-production/build-seq-job:v1.8-577bcc3-706
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --etcd
            - $(ETCD)
            - --bucket_name
            - $(BUCKET_NAME)
            - --local_disk_tmp_dir
            - /tmp
            - --db_host
            - $(DB_HOST)
            - --db_port
            - $(DB_PORT)
            - --db_name
            - $(POSTGRES_DB)
            - --db_user
            - $(POSTGRES_USER)
            - --redis_host_ps
            - $(PERSISTENT_REDIS_HOST)
            - --redis_port_ps
            - $(PERSISTENT_REDIS_PORT)
            - --db_pass
            - $(POSTGRES_PASSWORD)
            - --num_routines
            - $(NUM_ROUTINES)
            - --model_type
            - $(MODEL_TYPE)
            - --look_back_days
            - $(LOOK_BACK_DAYS)
            - --project_ids_to_skip
            - "11"
            envFrom:
            - configMapRef:
                name: config-etcd
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-bucket
            - configMapRef:
                name: config-memsql
            - configMapRef:
                name: config-redis
            - configMapRef:
                name: config-persistent-redis
            - configMapRef:
                name: config-buildseqjob
            - secretRef:
                name: secret-memsql
          restartPolicy: OnFailure
