apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    nodePool: shared-persistent-pool2
  name: cache-cleanup-filter-lists-job
spec:
  schedule: "1 2 3 4 5"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: shared-persistent-pool2
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: shared-persistent-pool2
          containers:
          - name: cache-cleanup-filter-lists-job
            image: us.gcr.io/factors-production/cache-cleanup-filter-lists-job:test
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --memsql_host
            - $(MEMSQL_HOST)
            - --memsql_port
            - $(MEMSQL_PORT)
            - --memsql_name
            - $(MEMSQL_DB)
            - --memsql_user
            - $(MEMSQL_USER)
            - --memsql_pass
            - $(MEMSQL_PASSWORD)
            - --memsql_cert
            - $(MEMSQL_CERTIFICATE)
            - --primary_datastore
            - "memsql"
            - --redis_host_ps
            - $(PERSISTENT_REDIS_HOST)
            - --redis_port_ps
            - $(PERSISTENT_REDIS_PORT)
            - --project_ids
            - "2"
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-memsql
            - configMapRef:
                name: config-redis
            - secretRef:
                name: secret-memsql
            - secretRef:
                name: secret-sentry
          restartPolicy: OnFailure
