apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: default-pool
  name: chat-data-job
spec:
  schedule: "0 00 * * *" # In UTC
  suspend: true
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: default-pool
          containers:
          - name: chat-data
            image: us.gcr.io/factors-production/chat-data:latest
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --chat_bucket
            - factors-staging-misc
            - --oauth_secret
            - $(GOOGLE_OAUTH_SECRET)
            - --developer_token
            - $(GOOGLE_ADWORDS_DEVELOPER_TOKEN)
            envFrom:
              - configMapRef:
                  name: config-env
              - secretRef:
                  name: secret-google
          restartPolicy: OnFailure