apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: persistent-pool-standard
  name: cleanup-goal-job
spec:
  schedule: "1 2 3 4 5" #On Trigger
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: persistent-pool-standard
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: persistent-pool-standard
          containers:
          - name: cleanup-goals-job
            image: us.gcr.io/factors-production/cleanup-goals-job:v0.010-18d3217
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --db_host
            - $(DB_HOST)
            - --db_port
            - $(DB_PORT)
            - --db_name
            - $(POSTGRES_DB)
            - --db_user
            - $(POSTGRES_USER)
            - --db_pass
            - $(POSTGRES_PASSWORD)
            - --sentry_dsn
            - $(SENTRY_DSN)
            - --gcp_project_id
            - $(GCP_PROJECT_ID)
            - --gcp_project_location
            - $(GCP_PROJECT_LOCATION)
            - --project_ids
            - ""
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-postgres
            - secretRef:
                name: secret-postgres
            - secretRef:
                name: secret-sentry
          restartPolicy: OnFailure
