apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: up-migration-pool1
  name: copy-user-properties-migration
spec:
  schedule: "1 2 3 4 5"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: up-migration-pool1
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: up-migration-pool1
          containers:
          - name: copy-user-properties-migration
            image: us.gcr.io/factors-production/copy-user-properties-migration:859291fb0-1542
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --db_host
            - $(DB_HOST_CLONE)
            - --db_port
            - $(DB_PORT)
            - --db_name
            - $(POSTGRES_DB)
            - --db_user
            - $(POSTGRES_USER)
            - --db_pass
            - $(POSTGRES_PASSWORD)
            - --sentry_dsn
            - $(SENTRY_DSN)
            - --project_ids
            - ""
            - --page_size
            - "10000"
            - --routines
            - "100"
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-postgres
            - secretRef:
                name: secret-sentry
            - secretRef:
                name: secret-postgres
            resources:
              requests:
                cpu: 23000
                memory: 10G
          restartPolicy: OnFailure
