apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    nodePool: shared-persistent-pool2
  name: default-segments-creation-job
spec:
  schedule: "1 2 3 4 5"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: shared-persistent-pool2
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: shared-persistent-pool2
          containers:
            - name: default-segments-creation-job
              image: us.gcr.io/factors-production/default-segments-creation-job:v0.01
              imagePullPolicy: IfNotPresent
              args:
                - --env
                - $(ENV)
                - --memsql_host
                - $(MEMSQL_HOST)
                - --memsql_port
                - $(MEMSQL_PORT)
                - --memsql_name
                - $(MEMSQL_DB)
                - --memsql_user
                - $(MEMSQL_USER)
                - --memsql_pass
                - $(MEMSQL_PASSWORD)
                - --memsql_cert
                - $(MEMSQL_CERTIFICATE)
                - --sentry_dsn
                - $(SENTRY_DSN)
                - --project_id
                - "*"
                - --primary_datastore
                - memsql
              envFrom:
                - configMapRef:
                    name: config-env
                - configMapRef:
                    name: config-memsql
                - secretRef:
                    name: secret-memsql
                - secretRef:
                    name: secret-sentry
          restartPolicy: OnFailure
