apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: shared-persistent-pool2
  name: event-trigger-alerts-job
spec:
  schedule: "1 2 3 4 5"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: shared-persistent-pool2
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: shared-persistent-pool2
          containers:
          - name: event-trigger-alerts-job
            image: us.gcr.io/factors-production/event-trigger-alerts-job:v20230112-hotfix-event-trigger
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --memsql_host
            - $(MEMSQL_HOST)
            - --memsql_port
            - $(MEMSQL_PORT)
            - --memsql_name
            - $(MEMSQL_DB)
            - --memsql_user
            - $(MEMSQL_USER)
            - --memsql_pass
            - $(MEMSQL_PASSWORD)
            - --memsql_cert
            - $(MEMSQL_CERTIFICATE)
            - --primary_datastore
            - "memsql"
            - --event_trigger_enabled
            - --event_trigger_enabled_project_ids
            - "2"
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-memsql
            - configMapRef:
                name: config-redis
            - secretRef:
                name: secret-memsql
            - secretRef:
                name: secret-sentry
          restartPolicy: OnFailure
