apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    nodePool: shared-persistent-pool2
  name: factors-deanon-monitoring
spec:
  schedule: "1 2 3 4 5" # In UTC
  successfulJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: shared-persistent-pool2
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: shared-persistent-pool2
          containers:
          - name: factors-deanon-monitoring
            image: us.gcr.io/factors-production/factors-deanon-monitoring:1.0
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --memsql_host
            - $(MEMSQL_HOST)
            - --memsql_is_psc_host
            - '1'
            - --memsql_port
            - $(MEMSQL_PORT)
            - --memsql_name
            - $(MEMSQL_DB)
            - --memsql_user
            - $(MEMSQL_USER)
            - --memsql_pass
            - $(MEMSQL_PASSWORD)
            - --memsql_cert
            - $(MEMSQL_CERTIFICATE)
            - --redis_host_ps
            - $(PERSISTENT_REDIS_HOST)
            - --redis_port_ps
            - $(PERSISTENT_REDIS_PORT)
            - --threshold_value
            - 0.3
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-memsql
            - configMapRef:
                name: config-persistent-redis
            - secretRef:
                name: secret-memsql
          restartPolicy: OnFailure