apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: persistent-pool-highmem
  name: google-search-console-sync-job
spec:
  schedule: "0 00 * * *" # In UTC
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  backoffLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: persistent-pool-highmem
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: persistent-pool-highmem
          containers:
          - name: google-search-console-sync
            image: us.gcr.io/factors-staging/google-search-console-etl:v0.01
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --oauth_secret
            - $(GOOGLE_OAUTH_SECRET)
            - --developer_token
            - $(GOOGLE_ADWORDS_DEVELOPER_TOKEN)
            - --data_service_host
            - $(DATA_SERVICE_HOST_URL)
            envFrom:
            - configMapRef:
                name: config-pythonappserver
            - configMapRef:
                name: config-env
            - secretRef:
                name: secret-google
          restartPolicy: OnFailure
