apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: shared-persistent-pool
  name: hubspot-enrich-job
spec:
  schedule: "0 21 * * *" # In UTC
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: shared-persistent-pool
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: shared-persistent-pool
          containers:
          - name: hubspot-enrich-job
            image: us.gcr.io/factors-production/hubspot-enrich-job:4e644a2a-2445
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --db_host
            - $(DB_HOST)
            - --db_port
            - $(DB_PORT)
            - --db_name
            - $(POSTGRES_DB)
            - --db_user
            - $(POSTGRES_USER)
            - --db_pass
            - $(POSTGRES_PASSWORD)
            - --redis_host
            - $(REDIS_HOST)
            - --redis_port
            - $(REDIS_PORT)
            - --sentry_dsn
            - $(SENTRY_DSN)
            - --redis_host_ps
            - $(PERSISTENT_REDIS_HOST)
            - --redis_port_ps
            - $(PERSISTENT_REDIS_PORT)
            - --gcp_project_id
            - $(GCP_PROJECT_ID)
            - --gcp_project_location
            - $(GCP_PROJECT_LOCATION)
            - --enable_property_type_from_db
            - --property_details_cache_size
            - "1000"
            - --num_project_routines
            - "1"
            - --whitelisted_project_ids_property_type_check_from_db
            - '*'
            - --cache_with_sorted_set
            - --num_unique_doc_routines
            - "100"
            - --task_management_lookback
            - "3"
            - --enable_hubspot_groups_by_project_id
            - "595"
            - --use_source_property_overwrite_by_project_id
            - 566,2,645,616
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-postgres
            - secretRef:
                name: secret-postgres
            - secretRef:
                name: secret-sentry
            - configMapRef:
                name: config-redis
            - configMapRef:
                name: config-persistent-redis
          restartPolicy: OnFailure
