apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hubspot-sync-job
spec:
  schedule: "0 18 * * *" # In UTC
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: default-pool
          containers:
          - name: hubspot-sync-job
            image: us.gcr.io/factors-production/hubspot-sync-job:v0.01-a182c1b
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --data_service_host
            - $(DATA_SERVICE_HOST_URL)
            envFrom:
            - configMapRef:
                name: config-env
          restartPolicy: OnFailure