apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: persistent-pool-highmem
  name: hubspot-enrich-job-dup
spec:
  schedule: "0 21 * * *" # In UTC
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: persistent-pool-highmem
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: persistent-pool-highmem
          containers:
          - name: hubspot-enrich-job-dup
            image: us.gcr.io/factors-production/hubspot-enrich-job:v0.82-2375b12d-1167
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --memsql_host
            - $(MEMSQL_HOST)
            - --memsql_port
            - $(MEMSQL_PORT)
            - --memsql_name
            - $(MEMSQL_DB)
            - --memsql_user
            - $(MEMSQL_USER)
            - --memsql_pass
            - $(MEMSQL_PASSWORD)
            - --memsql_cert
            - $(MEMSQL_CERTIFICATE)
            - --redis_host
            - $(REDIS_HOST_2)
            - --redis_port
            - $(REDIS_PORT_2)
            - --redis_host_ps
            - $(REDIS_HOST_2)
            - --redis_port_ps
            - $(REDIS_PORT_2)
            - --sentry_dsn
            - $(SENTRY_DSN)
            - --gcp_project_id
            - $(GCP_PROJECT_ID)
            - --gcp_project_location
            - $(GCP_PROJECT_LOCATION)
            - --primary_datastore
            - "memsql"
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-memsql
            - secretRef:
                name: secret-memsql
            - configMapRef:
                name: config-redis
            - secretRef:
                name: secret-sentry
            - configMapRef:
                name: config-persistent-redis
          restartPolicy: OnFailure
