apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: persistent-pool-standard
  name: instantiate-event-user-cache-job
spec:
  schedule: "1 2 3 4 5" # On Trigger
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: persistent-pool-standard
          containers:
          - name: instantiate-event-user-cache-job
            image: us.gcr.io/factors-production/instantiate-event-user-cache-job:v0.01-e8c91a1
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --db_host
            - $(DB_HOST)
            - --db_port
            - $(DB_PORT)
            - --db_name
            - $(POSTGRES_DB)
            - --db_user
            - $(POSTGRES_USER)
            - --redis_host_ps
            - $(PERSISTENT_REDIS_HOST)
            - --redis_port_ps
            - $(PERSISTENT_REDIS_PORT)
            - --db_pass
            - $(POSTGRES_PASSWORD)
            - --project_ids
            - "2"
            - --sentry_dsn
            - $(SENTRY_DSN)
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-postgres
            - configMapRef:
                name: config-redis
            - configMapRef:
                name: config-persistent-redis
            - secretRef:
                name: secret-postgres
            - secretRef:
                name: secret-sentry
          restartPolicy: OnFailure
