apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: shared-persistent-pool
  name: monitoring-job-memsql
spec:
  schedule: "*/5 * * * *" # every 15 minutes
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 30
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: shared-persistent-pool
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: shared-persistent-pool
          containers:
          - name: monitoring-job-memsql
            image: us.gcr.io/factors-production/monitoring:v0.15_eeb2024b
            imagePullPolicy: IfNotPresent
            args:
            - --integration_queue_threshold
            - "20000"
            - --slow_queries_threshold
            - "75"
            - --delayed_task_threshold
            - "2000"
            - --env
            - $(ENV)
            - --memsql_host
            - $(MEMSQL_HOST)
            - --memsql_port
            - $(MEMSQL_PORT)
            - --memsql_name
            - $(MEMSQL_DB)
            - --memsql_user
            - $(MEMSQL_ADMIN_USER)
            - --memsql_pass
            - $(MEMSQL_ADMIN_PASSWORD)
            - --memsql_cert
            - $(MEMSQL_CERTIFICATE)
            - --queue_redis_host
            - $(QUEUE_REDIS_HOST)
            - --queue_redis_port
            - $(QUEUE_REDIS_PORT)
            - --dup_queue_redis_host
            - $(DUP_QUEUE_REDIS_HOST)
            - --dup_queue_redis_port
            - $(DUP_QUEUE_REDIS_PORT)
            - --gcp_project_id
            - $(GCP_PROJECT_ID)
            - --gcp_project_location
            - $(GCP_PROJECT_LOCATION)
            - --sdk_queue_threshold
            - "50000"
            - --primary_datastore
            - memsql
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-memsql
            - configMapRef:
                name: config-queue-redis
            - secretRef:
                name: secret-memsql
          restartPolicy: OnFailure
