apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: persistent-pool-standard
  name: monitoring-job
spec:
  schedule: "*/15 * * * *" # every 15 minutes
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 30
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: persistent-pool-standard
          containers:
          - name: monitoring-job
            image: us.gcr.io/factors-production/monitoring:v0.15_eeb2024b
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --db_host
            - $(DB_HOST)
            - --db_port
            - $(DB_PORT)
            - --db_name
            - $(POSTGRES_DB)
            - --db_user
            - $(POSTGRES_USER)
            - --db_pass
            - $(POSTGRES_PASSWORD)
            - --queue_redis_host
            - $(QUEUE_REDIS_HOST)
            - --queue_redis_port
            - $(QUEUE_REDIS_PORT)
            - --gcp_project_id
            - $(GCP_PROJECT_ID)
            - --gcp_project_location
            - $(GCP_PROJECT_LOCATION)
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-postgres
            - configMapRef:
                name: config-queue-redis
            - secretRef:
                name: secret-postgres
          restartPolicy: OnFailure
