apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: shared-persistent-pool
  name: monitoring-job
spec:
  schedule: "*/5 * * * *" # every 15 minutes
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 30
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: shared-persistent-pool
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: shared-persistent-pool
          containers:
          - name: monitoring-job
            image: us.gcr.io/factors-production/monitoring:v0.15_eeb2024b
            imagePullPolicy: IfNotPresent
            args:
            - --sdk_queue_threshold
            - "15000"
            - --integration_queue_threshold
            - "20000"
            - --slow_queries_threshold
            - "75"
            - --delayed_task_threshold
            - "2000"
            - --env
            - $(ENV)
            - --db_host
            - $(DB_HOST)
            - --db_port
            - $(DB_PORT)
            - --db_name
            - $(POSTGRES_DB)
            - --db_user
            - $(POSTGRES_USER)
            - --db_pass
            - $(POSTGRES_PASSWORD)
            - --queue_redis_host
            - $(QUEUE_REDIS_HOST)
            - --queue_redis_port
            - $(QUEUE_REDIS_PORT)
            - --gcp_project_id
            - $(GCP_PROJECT_ID)
            - --gcp_project_location
            - $(GCP_PROJECT_LOCATION)
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-postgres
            - configMapRef:
                name: config-queue-redis
            - secretRef:
                name: secret-postgres
          restartPolicy: OnFailure
