apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    nodePool: adhoc-batch-pool
  name: sixsignal-report-job
spec:
  schedule: "1 2 3 4 5" # In UTC
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
            nodePool: adhoc-batch-pool
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: adhoc-batch-pool
          containers:
          - name: sixsignal-report-job
            image: us.gcr.io/factors-production/sixsignal-report-job:1.0
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --bucket_name
            - $(BUCKET_NAME)
            - --model_bucket_name
            - factors-production-models
            - --local_disk_tmp_dir
            - /tmp
            - --memsql_host
            - $(MEMSQL_HOST)
            - --memsql_port
            - $(MEMSQL_PORT)
            - --memsql_name
            - $(MEMSQL_DB)
            - --memsql_user
            - $(MEMSQL_USER)
            - --memsql_pass
            - $(MEMSQL_PASSWORD)
            - --memsql_cert
            - $(MEMSQL_CERTIFICATE)
            - --aws_region
            - $(AWS_REGION)
            - --aws_key
            - $(AWS_KEY)
            - --aws_secret
            - $(AWS_SECRET)
            - --email_sender
            - $(EMAIL_SENDER)
            - --app_domain
            - $(APP_DOMAIN)
            - --use_bucket_v2
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-bucket
            - configMapRef:
                name: config-memsql
            - secretRef:
                name: secret-memsql
            - secretRef:
                name: secret-aws
          restartPolicy: OnFailure