package util

// Note: Copy of default properties from PATH_TO_REPO/factors/backend/src/factors/util/properties.go
// Do not change directly.

// Event Properites
var EP_INTERNAL_IP string = "$ip"
var EP_LOCATION_LATITUDE string = "$location_lat"
var EP_LOCATION_LONGITUDE string = "$location_lng"
var EP_PAGE_TITLE string = "$page_title"
var EP_PAGE_DOMAIN string = "$page_domain"
var EP_PAGE_RAW_URL string = "$page_raw_url"
var EP_PAGE_URL string = "$page_url"
var EP_REFERRER string = "$referrer"
var EP_REFERRER_DOMAIN string = "$referrer_domain"
var EP_REFERRER_URL string = "$referrer_url"
var EP_PAGE_LOAD_TIME string = "$page_load_time"
var EP_PAGE_SPENT_TIME string = "$page_spent_time"
var EP_SEGMENT_EVENT_VERSION string = "$segment_event_version"

var EP_CAMPAIGN string = "$campaign"
var EP_CAMPAIGN_ID string = "$campaign_id"
var EP_SOURCE string = "$source"
var EP_MEDIUM string = "$medium"
var EP_KEYWORD string = "$keyword"
var EP_KEYWORD_MATCH_TYPE string = "$keyword_match_type"
var EP_CONTENT string = "$content"
var EP_AD_GROUP string = "$ad_group"
var EP_AD_GROUP_ID string = "$ad_group_id"
var EP_CREATIVE string = "$creative"
var EP_GCLID string = "$gclid"
var EP_FBCLID string = "$fbclid"
var EP_COST string = "$cost"
var EP_REVENUE string = "$revenue"

// User Properties
var UP_PLATFORM string = "$platform"
var UP_BROWSER string = "$browser"
var UP_BROWSER_VERSION string = "$browser_version"
var UP_BROWSER_WITH_VERSION string = "$browser_with_version"
var UP_USER_AGENT string = "$user_agent"
var UP_OS string = "$os"
var UP_OS_VERSION string = "$os_version"
var UP_OS_WITH_VERSION string = "$os_with_version"
var UP_SCREEN_WIDTH string = "$screen_width"
var UP_SCREEN_HEIGHT string = "$screen_height"
var UP_SCREEN_DENSITY string = "$screen_density"
var UP_LANGUAGE string = "$language"
var UP_LOCALE string = "$locale"
var UP_DEVICE_ID string = "$device_id"
var UP_DEVICE_NAME string = "$device_name"
var UP_DEVICE_ADVERTISING_ID string = "$device_advertising_id"
var UP_DEVICE_BRAND string = "$device_brand"
var UP_DEVICE_MODEL string = "$device_model"
var UP_DEVICE_TYPE string = "$device_type"
var UP_DEVICE_FAMILY string = "$device_family"
var UP_DEVICE_MANUFACTURER string = "$device_manufacturer"
var UP_DEVICE_CARRIER string = "$device_carrier"
var UP_DEVICE_ADTRACKING_ENABLED string = "$device_ad_tracking_enabled"
var UP_NETWORK_BLUETOOTH string = "$network_bluetooth"
var UP_NETWORK_CARRIER string = "$network_carrier"
var UP_NETWORK_CELLULAR string = "$network_cellular"
var UP_NETWORK_WIFI string = "$network_wifi"
var UP_APP_NAME string = "$app_name"
var UP_APP_NAMESPACE string = "$app_namespace"
var UP_APP_VERSION string = "$app_version"
var UP_APP_BUILD string = "$app_build"
var UP_COUNTRY string = "$country"
var UP_CITY string = "$city"
var UP_REGION string = "$region"
var UP_TIMEZONE string = "$timezone"
var UP_SEGMENT_CHANNEL string = "$segment_channel" // from segement (browser, client, etc.,).

var UP_CUSTOMER_USER_ID string = "$customer_user_id"
var UP_EMAIL string = "$email"
var UP_FIRST_NAME string = "$first_name"
var UP_LAST_NAME string = "$last_name"
var UP_PHONE string = "$phone"
var UP_INITIAL_PAGE_URL string = "$initial_page_url"
var UP_INITIAL_PAGE_DOMAIN string = "$initial_page_domain"
var UP_INITIAL_PAGE_RAW_URL string = "$initial_page_raw_url"
var UP_INITIAL_PAGE_LOAD_TIME string = "$initial_page_load_time"
var UP_INITIAL_PAGE_SPENT_TIME string = "$initial_page_spent_time"
var UP_INITIAL_CAMPAIGN string = "$initial_campaign"
var UP_INITIAL_CAMPAIGN_ID string = "$initial_campaign_id"
var UP_INITIAL_SOURCE string = "$initial_source"
var UP_INITIAL_MEDIUM string = "$initial_medium"
var UP_INITIAL_KEYWORD string = "$initial_keyword"
var UP_INITIAL_KEYWORD_MATCH_TYPE string = "$initial_keyword_match_type"
var UP_INITIAL_CONTENT string = "$initial_content"
var UP_INITIAL_ADGROUP string = "$initial_adgroup"
var UP_INITIAL_ADGROUP_ID string = "$initial_adgroup_id"
var UP_INITIAL_CREATIVE string = "$initial_creative"
var UP_INITIAL_GCLID string = "$initial_gclid"
var UP_INITIAL_FBCLID string = "$initial_fbclid"
