apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    layer: appserver-memsql
    env: staging
    project: factors-staging
    nodePool: factors-staging-node-pool
  name: appserver-memsql
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      layer: appserver-memsql
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:      
      labels:
        layer: appserver-memsql
        nodePool: factors-staging-node-pool
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: factors-staging-node-pool
      containers:
      - name: appserver-memsql
        image: us.gcr.io/factors-staging/app-server:65072f80c
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: workdir
          mountPath: /usr/local/var/factors/config
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          limits:
            memory: "1500M"
            cpu: "1"
          requests:
            memory: "1000M"
            cpu: ".5"
        securityContext: {}
        readinessProbe:
          httpGet:
            path: /mql/status?s=k8_rp
            scheme: HTTP
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /mql/status?s=k8_lp
            scheme: HTTP
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        args:          
          - --env
          - $(ENV)
          - --app_name
          - "appserver_memsql"
          - --api_http_port
          - $(API_HTTP_PORT)
          - --etcd
          - $(ETCD)
          - --db_host
          - $(MEMSQL_HOST)
          - --db_port
          - $(MEMSQL_PORT)
          - --db_name
          - $(MEMSQL_DB)
          - --db_user
          - $(MEMSQL_USER)
          - --db_pass
          - $(MEMSQL_PASSWORD)
          - --memsql_cert
          - $(MEMSQL_CERTIFICATE)
          - --redis_host
          - $(REDIS_HOST)
          - --redis_port
          - $(REDIS_PORT)
          - --redis_host_ps
          - $(PERSISTENT_REDIS_HOST)
          - --redis_port_ps
          - $(PERSISTENT_REDIS_PORT)
          - --geo_loc_path
          - $(GEO_LOC_FILE_PATH)
          - --api_domain
          - $(API_DOMAIN)
          - --app_domain
          - $(APP_DOMAIN)
          - --app_old_domain
          - $(APP_OLD_HOST_URL)
          - --aws_region
          - $(AWS_REGION)
          - --aws_key
          - $(AWS_KEY)
          - --aws_secret
          - $(AWS_SECRET)
          - --email_sender
          - $(EMAIL_SENDER)
          - --login_token_map
          - $(LOGIN_TOKEN_MAP)
          - --admin_login_email
          - $(ADMIN_LOGIN_EMAIL)
          - --admin_login_token
          - $(ADMIN_LOGIN_TOKEN)
          - --facebook_app_id
          - $(FACEBOOK_APP_ID)
          - --facebook_app_secret
          - $(FACEBOOK_APP_SECRET)
          - --linkedin_client_id
          - $(LINKEDIN_CLIENT_ID)
          - --linkedin_client_secret
          - $(LINKEDIN_CLIENT_SECRET)
          - --salesforce_app_secret
          - $(SALESFORCE_APP_SECRET)
          - --salesforce_app_id
          - $(SALESFORCE_APP_ID)
          - --device_detector_path
          - $(DEVICE_DETECTOR_DATA_PATH)
          - --sentry_dsn
          - $(SENTRY_DSN)
          - --gcp_project_id
          - $(GCP_PROJECT_ID)
          - --gcp_project_location
          - $(GCP_PROJECT_LOCATION)
          - --allow_smart_event_rule_creation
          - --lookback_window_event_user_cache
          - "10"
          - --attribution_debug
          - 0
          - --project_analytics_whitelisted_uuids
          - a2d600fc-75b4-4384-9bda-7a039f6e64c9
          - --primary_datastore
          - memsql
          - --disable_mql_db_writes
          - --disable_mql_redis_writes
          - --linkedin_member_company_config_project_ids
          - ""
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP              
        envFrom:
        - configMapRef:
            name: config-appserver
        - configMapRef:
            name: config-etcd
        - configMapRef:
            name: config-env
        - configMapRef:
            name: config-memsql
        - configMapRef:
            name: config-redis
        - configMapRef:
            name: config-persistent-redis
        - configMapRef:
            name: config-add-session-job
        - secretRef:
            name: secret-memsql
        - secretRef:
            name: secret-aws
        - secretRef:
            name: secret-login-token
        - secretRef:
            name: secret-facebook
        - secretRef:
            name: secret-linkedin
        - secretRef:
            name: secret-sentry
        - secretRef:
            name: secret-salesforce
      initContainers:
      - name: fetch-geolocation-file
        image: google/cloud-sdk:229.0.0-alpine
        command:
        - gsutil
        - cp
        - gs://factors-staging/GeoLite2-City.mmdb
        - /workdir/GeoLite2-City.mmdb
        volumeMounts:
        - name: workdir
          mountPath: "/workdir"
      - name: fetch-device-detector-data
        image: google/cloud-sdk:229.0.0-alpine
        command:
        - gsutil 
        - rsync 
        - -r 
        - gs://factors-staging/device_detector_regexs
        - /workdir
        volumeMounts:
        - name: workdir
          mountPath: "/workdir"
      volumes:
      - name: workdir
        emptyDir: {}
