apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    layer: appserver
    env: staging
    project: factors-staging
  name: appserver
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      layer: appserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:      
      labels:
        layer: appserver
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: factors-staging-node-pool
      containers:
      - name: appserver
        image: us.gcr.io/factors-staging/app-server:v3.16-1d6b430-721
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: workdir
          mountPath: /usr/local/var/factors/config
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          limits:
            memory: "1500M"
            cpu: "1"
          requests:
            memory: "1000M"
            cpu: ".5"
        securityContext: {}
        readinessProbe:
          httpGet:
            path: /status?s=k8_rp
            scheme: HTTP
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /status?s=k8_lp
            scheme: HTTP
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        args:          
          - --env
          - $(ENV)
          - --api_http_port
          - $(API_HTTP_PORT)
          - --etcd
          - $(ETCD)
          - --db_host
          - $(DB_HOST)
          - --db_port
          - $(DB_PORT)
          - --db_name
          - $(POSTGRES_DB)
          - --db_user
          - $(POSTGRES_USER)
          - --db_pass
          - $(POSTGRES_PASSWORD)
          - --redis_host
          - $(REDIS_HOST)
          - --redis_port
          - $(REDIS_PORT)
          - --redis_host_ps
          - $(PERSISTENT_REDIS_HOST)
          - --redis_port_ps
          - $(PERSISTENT_REDIS_PORT)
          - --geo_loc_path
          - $(GEO_LOC_FILE_PATH)
          - --api_domain
          - $(API_DOMAIN)
          - --app_domain
          - $(APP_DOMAIN)
          - --aws_region
          - $(AWS_REGION)
          - --aws_key
          - $(AWS_KEY)
          - --aws_secret
          - $(AWS_SECRET)
          - --email_sender
          - $(EMAIL_SENDER)
          - --login_token_map
          - $(LOGIN_TOKEN_MAP)
          - --admin_login_email
          - $(ADMIN_LOGIN_EMAIL)
          - --admin_login_token
          - $(ADMIN_LOGIN_TOKEN)
          - --facebook_app_id
          - $(FACEBOOK_APP_ID)
          - --facebook_app_secret
          - $(FACEBOOK_APP_SECRET)
          - --salesforce_app_secret
          - $(SALESFORCE_APP_SECRET)
          - --salesforce_app_id
          - $(SALESFORCE_APP_ID)
          - --skip_session_project_ids
          - $(OFFLINE_SESSION_PROJECT_IDS)
          - --sentry_dsn
          - $(SENTRY_DSN)
          - --gcp_project_id
          - $(GCP_PROJECT_ID)
          - --gcp_project_location
          - $(GCP_PROJECT_LOCATION)
          - --whitelisted_projects_ids_event_user_cache
          - "2,37"
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP              
        envFrom:
        - configMapRef:
            name: config-appserver
        - configMapRef:
            name: config-etcd
        - configMapRef:
            name: config-env
        - configMapRef:
            name: config-postgres
        - configMapRef:
            name: config-redis
        - configMapRef:
            name: config-persistent-redis
        - configMapRef:
            name: config-add-session-job
        - secretRef:
            name: secret-postgres
        - secretRef:
            name: secret-aws
        - secretRef:
            name: secret-login-token
        - secretRef:
            name: secret-facebook
        - secretRef:
            name: secret-sentry
        - secretRef:
            name: secret-salesforce
      initContainers:
      - name: fetch-geolocation-file
        image: google/cloud-sdk:229.0.0-alpine
        command:
        - gsutil
        - cp
        - gs://factors-staging/GeoLite2-City.mmdb
        - /workdir/GeoLite2-City.mmdb
        volumeMounts:
        - name: workdir
          mountPath: "/workdir"
      - name: fetch-device-detector-data
        image: google/cloud-sdk:229.0.0-alpine
        command:
        - gsutil 
        - rsync 
        - -r 
        - gs://factors-staging/device_detector_regexs
        - /workdir
        volumeMounts:
        - name: workdir
          mountPath: "/workdir"
      volumes:
      - name: workdir
        emptyDir: {}
