apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    layer: dup-queue-redis
    env: staging
    project: factors-staging
    nodePool: factors-staging-node-pool
  name: dup-queue-redis
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      layer: dup-queue-redis
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:      
      labels:
        layer: dup-queue-redis
        nodePool: factors-staging-node-pool
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: factors-staging-node-pool
      terminationGracePeriodSeconds: 30
      volumes:
        - name: dup-queue-redis-storage
          persistentVolumeClaim:
            claimName: dup-queue-redis-pvc
      containers:
      - name: dup-queue-redis
        image: us.gcr.io/factors-staging/queue-redis:v0.01-e3fc852-562
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: dup-queue-redis-storage
          mountPath: "/usr/local/var/db/redis"
        resources:
          requests:
            memory: "100M"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext: {}
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 10