apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
spec:
  selector:
    matchLabels:
      app: etcd
  serviceName: "etcd"
  replicas: 1
  template:
    metadata:
      labels:
        app: etcd
        env: staging
        project: factors-staging
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: etcd-storage
          persistentVolumeClaim:
            claimName: etcd-pvc
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.2.4
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          limits:
            memory: "500M"
            cpu: "1"
          requests:
            memory: "250M"
            cpu: ".5"
        command:
         - /usr/local/bin/etcd
        readinessProbe:
          tcpSocket:
            port: 2379
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 2379
          initialDelaySeconds: 5
          periodSeconds: 10
        args:
          - --listen-client-urls
          - http://$(MY_POD_IP):2379
          - --advertise-client-urls
          - http://$(MY_POD_IP):2379
          - --data-dir
          - "/data/etcd/"
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        volumeMounts:
        - mountPath: "/data/etcd"
          name: etcd-storage