apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    layer: deployment
  name: etcd
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      layer: etcd
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:      
      labels:
        layer: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.2.4
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        command:
         - /usr/local/bin/etcd
        readinessProbe:
          tcpSocket:
            port: 2379
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 2379
          initialDelaySeconds: 10
          periodSeconds: 10
        args:
          - --listen-client-urls
          - http://$(MY_POD_IP):2379
          - --advertise-client-urls
          - http://$(MY_POD_IP):2379
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP