apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: frontend
    env: staging
    project: factors-staging
    nodePool: factors-staging-node-pool
  name: frontend
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
        nodePool: factors-staging-node-pool
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: factors-staging-node-pool
      containers:
      - image: us.gcr.io/factors-staging/frontend:v0.10-beta_ed8453b
        imagePullPolicy: IfNotPresent
        name: frontend
        resources:
          limits:
            memory: "200M"
            cpu: "1"
          requests:
            memory: "100M"
            cpu: ".5"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10