apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    layer: memsql-replicator
    env: staging
    project: factors-staging
  name: memsql-replicator
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      layer: memsql-replicator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:      
      labels:
        layer: memsql-replicator
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-persistent-pool
      containers:
      - name: memsql-replicator
        image: us.gcr.io/factors-staging/memsql-replicator:v0.01-xxx
        volumeMounts:
        - name: workdir
          mountPath: /usr/local/var/factors/config
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext: {}
        args:
          - --env
          - $(ENV)
          - --db_host
          - $(DB_HOST)
          - --db_port
          - $(DB_PORT)
          - --db_name
          - $(POSTGRES_DB)
          - --db_user
          - $(POSTGRES_USER)
          - --db_pass
          - $(POSTGRES_PASSWORD)
          - --sentry_dsn
          - $(SENTRY_DSN)
          - --memsql_dsn
          - "<USER>:<PASSWORD>@tcp(<HOST>:3306)/factors?charset=utf8mb4&parseTime=True&loc=Local"
          - --project_ids
          - "*"
          - --page_size
          - "10000"
        envFrom:
        - configMapRef:
            name: config-env
        - configMapRef:
            name: config-postgres
        - secretRef:
            name: secret-postgres
        - secretRef:
            name: secret-sentry
      volumes:
      - name: workdir
        emptyDir: {}
