apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    layer: postgres
  name: postgres
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      layer: postgres
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:      
      labels:
        layer: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:11.1
        ports:
        - containerPort: 5432
        # https://stackoverflow.com/questions/51168558/how-to-mount-a-postgresql-volume-using-aws-ebs-in-kubernete/51174380#51174380
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-volume
          subPath: postgres
        imagePullPolicy: IfNotPresent
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext: {}        
        env:
        envFrom:        
        - configMapRef:
            name: config-postgres
        - secretRef:
            name: secret-postgres
      volumes:
        - name: postgres-volume
          # This GCE PD must already exist
          gcePersistentDisk:
            pdName: postgres-staging
            fsType: ext4