apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    layer: pythonappserver
    env: staging
    project: factors-staging
    nodePool: factors-staging-node-pool
  name: pythonappserver
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      layer: pythonappserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:      
      labels:
        layer: pythonappserver
        nodePool: factors-staging-node-pool
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: factors-staging-node-pool
      containers:
      - name: pythonappserver
        image: us.gcr.io/factors-staging/python-server:v0.13-4bcdb5e2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8091
        volumeMounts:
        - name: workdir
          mountPath: $(ADWORDS_SERVER_PATH)
        resources:
          requests:
            memory: "100M"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext: {}
        readinessProbe:
          tcpSocket:
            port: 8091
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8091
          initialDelaySeconds: 10
          periodSeconds: 10
        args:
          - --env
          - $(ENV)
          - --port
          - $(ADWORDS_SERVER_PORT)
          - --chat_bucket
          - $(CHAT_DATA_BUCKET)
          - --host_url
          - $(API_HOST_URL)
          - --api_host_url
          - $(DATA_SERVICE_HOST_URL)
          - --app_host_url
          - $(APP_HOST_URL)
          - --oauth_secret
          - $(GOOGLE_OAUTH_SECRET)
          - --developer_token
          - $(GOOGLE_ADWORDS_DEVELOPER_TOKEN)
          - --sentry_dsn
          - $(SENTRY_DSN)
          - --server_name
          - "pythonappserver"
        envFrom:
        - configMapRef:
            name: config-pythonappserver
        - configMapRef:
            name: config-env
        - secretRef:
            name: secret-google
        - secretRef:
            name: secret-sentry
      volumes:
      - name: workdir
        emptyDir: {}