apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    layer: sdk-request-worker-dup
    env: staging
    project: factors-staging
    nodePool: factors-staging-node-pool
  name: sdk-request-worker-dup
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      layer: sdk-request-worker-dup
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:      
      labels:
        layer: sdk-request-worker-dup
        nodePool: factors-staging-node-pool
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: factors-staging-node-pool
      containers:
      - name: sdk-request-worker-dup
        image: us.gcr.io/factors-staging/sdk-request-worker:859291fb0-1542
        volumeMounts:
        - name: workdir
          mountPath: /usr/local/var/factors/config
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          requests:
            memory: "100M"
        securityContext: {}
        args:
          - --env
          - $(ENV)
          - --memsql_host
          - $(MEMSQL_HOST)
          - --memsql_port
          - $(MEMSQL_PORT)
          - --memsql_name
          - $(MEMSQL_DB)
          - --memsql_user
          - $(MEMSQL_USER)
          - --memsql_pass
          - $(MEMSQL_PASSWORD)
          - --memsql_cert
          - $(MEMSQL_CERTIFICATE)
          - --redis_host
          - $(REDIS_HOST_2)
          - --redis_port
          - $(REDIS_PORT_2)
          - --redis_host_ps
          - $(REDIS_HOST_2)
          - --redis_port_ps
          - $(REDIS_PORT_2)
          - --queue_redis_host
          - $(QUEUE_REDIS_HOST)
          - --queue_redis_port
          - $(QUEUE_REDIS_PORT)
          - --dup_queue_redis_host
          - $(DUP_QUEUE_REDIS_HOST)
          - --dup_queue_redis_port
          - $(DUP_QUEUE_REDIS_PORT)
          - --geo_loc_path
          - $(GEO_LOC_FILE_PATH)
          - --worker_concurrency
          - "10"
          - --device_detector_path
          - $(DEVICE_DETECTOR_DATA_PATH)
          - --sentry_dsn
          - $(SENTRY_DSN)
          - --gcp_project_id
          - $(GCP_PROJECT_ID)
          - --gcp_project_location
          - $(GCP_PROJECT_LOCATION)
          - --primary_datastore
          - "memsql"
          - --ontable_user_properties_allowed_projects
          - "*"
          - --deprecate_user_properties_table_read_projects
          - "*"
          - --enable_sdk_and_integration_request_queue_duplication
          - --cache_with_sorted_set
        envFrom:
        - configMapRef:
            name: config-appserver
        - configMapRef:
            name: config-env
        - configMapRef:
            name: config-memsql
        - configMapRef:
            name: config-redis
        - configMapRef:
            name: config-persistent-redis
        - configMapRef:
            name: config-add-session-job
        - secretRef:
            name: secret-memsql
        - secretRef:
            name: secret-sentry
        - configMapRef:
            name: config-queue-redis
      initContainers:
      - name: fetch-geolocation-file
        image: google/cloud-sdk:229.0.0-alpine
        command:
        - gsutil
        - cp
        - gs://factors-staging/GeoLite2-City.mmdb
        - /workdir/GeoLite2-City.mmdb
        volumeMounts:
        - name: workdir
          mountPath: "/workdir"  
      - name: fetch-device-detector-data
        image: google/cloud-sdk:229.0.0-alpine
        command:
        - gsutil 
        - rsync 
        - -r 
        - gs://factors-staging/device_detector_regexs
        - /workdir
        volumeMounts:
        - name: workdir
          mountPath: "/workdir" 
      volumes:
      - name: workdir
        emptyDir: {}
