apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    layer: sdkserver
    env: staging
    project: factors-staging
    nodePool: factors-staging-node-pool
  name: sdkserver
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      layer: sdkserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:      
      labels:
        layer: sdkserver
        nodePool: factors-staging-node-pool
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: factors-staging-node-pool
      containers:
      - name: sdkserver
        image: us.gcr.io/factors-staging/sdk-server:v1.13-1d6b430-721
        ports:
        - containerPort: 8085
        volumeMounts:
        - name: workdir
          mountPath: /usr/local/var/factors/config
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          requests:
            memory: "100M"
        securityContext: {}
        readinessProbe:
          tcpSocket:
            port: 8085
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8085
          initialDelaySeconds: 10
          periodSeconds: 10
        args:
          - --env
          - $(ENV)
          - --port
          - $(SDK_SERVER_PORT)
          - --memsql_host
          - $(MEMSQL_HOST)
          - --memsql_port
          - $(MEMSQL_PORT)
          - --memsql_name
          - $(MEMSQL_DB)
          - --memsql_user
          - $(MEMSQL_OLTP_USER)
          - --memsql_pass
          - $(MEMSQL_PASSWORD)
          - --memsql_cert
          - $(MEMSQL_CERTIFICATE)
          - --redis_host
          - $(REDIS_HOST)
          - --redis_port
          - $(REDIS_PORT)
          - --queue_redis_host
          - $(PERSISTENT_REDIS_HOST)
          - --queue_redis_port
          - $(PERSISTENT_REDIS_PORT)
          - --geo_loc_path
          - $(GEO_LOC_FILE_PATH)
          - --sdk_request_queue_project_tokens
          - $(SDK_REQUEST_QUEUE_PROJECT_TOKENS)
          - --segment_request_queue_project_tokens
          - $(SEGMENT_REQUEST_QUEUE_PROJECT_TOKENS)
          - --sentry_dsn
          - $(SENTRY_DSN)
          - --redis_host_ps
          - $(PERSISTENT_REDIS_HOST)
          - --redis_port_ps
          - $(PERSISTENT_REDIS_PORT)
          - --gcp_project_id
          - $(GCP_PROJECT_ID)
          - --gcp_project_location
          - $(GCP_PROJECT_LOCATION)
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP              
        envFrom:
        - configMapRef:
            name: config-sdkserver
        - configMapRef:
            name: config-appserver
        - configMapRef:
            name: config-env
        - configMapRef:
            name: config-redis
        - configMapRef:
            name: config-persistent-redis
        - configMapRef:
            name: config-add-session-job
        - configMapRef:
            name: config-memsql
        - secretRef:
            name: secret-memsql
        - secretRef:
            name: secret-sentry
      initContainers:
      - name: fetch-geolocation-file
        image: google/cloud-sdk:229.0.0-alpine
        command:
        - gsutil
        - cp
        - gs://factors-staging/GeoLite2-City.mmdb
        - /workdir/GeoLite2-City.mmdb
        volumeMounts:
        - name: workdir
          mountPath: "/workdir"  
      - name: fetch-device-detector-data
        image: google/cloud-sdk:229.0.0-alpine
        command:
        - gsutil 
        - rsync 
        - -r 
        - gs://factors-staging/device_detector_regexs
        - /workdir
        volumeMounts:
        - name: workdir
          mountPath: "/workdir"
      volumes:
      - name: workdir
        emptyDir: {}
