apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    layer: memsql-studio
    env: production
    project: factors-production
  name: memsql-studio
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      layer: memsql-studio
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:      
      labels:
        layer: memsql-studio
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: persistent-pool-standard
      containers:
      - name: memsql-studio
        image: us.gcr.io/factors-production/memsql-studio:v0.01-xxx
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext: {}  
      volumes:
      - name: workdir
        emptyDir: {}
