apiVersion: v1
kind: Service
metadata:
  name: memsql-studio-service
  namespace: default
  labels:
    env: production
    layer: memsql-studio
    project: factors-production
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    layer: memsql-studio
  sessionAffinity: None
  type: ClusterIP