apiVersion: v1
kind: PersistentVolume
metadata:
  name: dup-queue-redis-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: factors-production-dup-queue-redis-disk
    fsType: ext4