apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "persistent-redis-pvc-new"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: ""
  resources:
    requests:
      storage: "300Gi"
  volumeName: "persistent-redis-pv-new"