apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "persistent-redis-pvc"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: ""
  resources:
    requests:
      storage: "100Gi"
  volumeName: "persistent-redis-pv"