apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-redis-pv-new
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: persistent-redis-disk-new
    fsType: ext4