apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "etcd-pvc"
  labels:
    env: production
    project: factors-production
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: ""
  resources:
    requests:
      storage: "25Gi"
  volumeName: "etcd-pv"