apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: queue-redis-2-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: ""
  resources:
    requests:
      storage: "25Gi"
  volumeName: queue-redis-2-pv