apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dup-queue-redis-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: ""
  resources:
    requests:
      storage: "25Gi"
  volumeName: dup-queue-redis-pv