apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-redis-pv
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: factors-staging-persistent-redis-disk
    fsType: ext4