# Create a gce persistent disk
# 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-pv
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: factors-staging-1-etcd
    fsType: ext4