apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "etcd-pvc"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: ""
  resources:
    requests:
      storage: "20Gi"
  volumeName: "etcd-pv"