export const SET_ACCOUNT_PAYLOAD = 'SET_ACCOUNT_PAYLOAD';
export const SET_ACTIVE_SEGMENT = 'SET_ACTIVE_SEGMENT';
export const UPDATE_ACCOUNT_PAYLOAD = 'UPDATE_ACCOUNT_PAYLOAD';
export const SET_ACCOUNT_SEGMENT_MODAL = 'SET_ACCOUNT_SEGMENT_MODAL';
export const ENABLE_NEW_SEGMENT_MODE = 'ENABLE_NEW_SEGMENT_MODE';
export const DISABLE_NEW_SEGMENT_MODE = 'DISABLE_NEW_SEGMENT_MODE';
export const SET_FILTERS_DIRTY = 'SET_FILTERS_DIRTY';
export const SET_EXIT_CONFIRMATION_MODAL = 'SET_EXIT_CONFIRMATION_MODAL';
