export const SET_ACCOUNT_PAYLOAD = 'SET_ACCOUNT_PAYLOAD';
export const SET_ACTIVE_SEGMENT = 'SET_ACTIVE_SEGMENT';
export const UPDATE_ACCOUNT_PAYLOAD = 'UPDATE_ACCOUNT_PAYLOAD';
export const SET_ACCOUNT_SEGMENT_MODAL = 'SET_ACCOUNT_SEGMENT_MODAL';
