apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: yourstory-add-properties-job
spec:
  schedule: "0 * * * *" # every 1 hour
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            layer: jobs
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: persistent-pool-highmem-jobs2
          containers:
          - name: yourstory-add-properties-job
            image: us.gcr.io/factors-production/yourstory-add-properties-job:v0.01-xxxxx
            imagePullPolicy: IfNotPresent
            args:
            - --env
            - $(ENV)
            - --db_host
            - $(DB_HOST)
            - --db_port
            - $(DB_PORT)
            - --db_name
            - $(POSTGRES_DB)
            - --db_user
            - $(POSTGRES_USER)
            - --db_pass
            - $(POSTGRES_PASSWORD)
            - max_lookback_days
            - "1"
            envFrom:
            - configMapRef:
                name: config-env
            - configMapRef:
                name: config-postgres
          restartPolicy: OnFailure
