apiVersion: v1
kind: Secret
metadata:
   name: secret-chargebee
   labels:
    env: staging
    project: factors-staging
type: Opaque
data:
   CHARGEBEE_API_KEY: "dGVzdF85aXhHdFBLQmg2Y2RObU9NMGZIQ25BUmJrUUFpMGNkU1pp"
   CHARGEBEE_SITE_NAME: "ZmFjdG9ycy10ZXN0"