apiVersion: v1
kind: Secret
metadata:
   name: secret-teams
   labels:
    env: staging
    project: factors-staging
type: Opaque
data:
  TEAMS_APP_TENANT_ID: "Y2E4NTc1YzItOGY1Ny00YjEwLWJiMzktNDU5ZDU4ODA5Yzll"
  TEAMS_APP_CLIENT_ID: "YjYwY2QyZmItZTg2OS00OTQwLTlhYWQtMDk4ZDU1MWY4MjE3"
  TEAMS_APP_CLIENT_SECRET: "RGJDOFF+c2k0bmc3flo4QmtHb01NQVgzOTZPdk9pdmZiU1lwQ2JhWA=="