user_data_file_name_prefix: "user_acme"
activity_time_in_seconds: 3600
real_time: false
user_id_prefix: U
new_user_poll_time: 10
new_user_probablity: 0.5
per_tick_new_user_seed_count: 30
custom_user_attribute_probablity: 0.2
custom_event_attribute_probablity: 0
bring_existing_user: 0.5
user_segments: 
  segment1:
    number_of_users: 1000
    activity_ticker_in_seconds: 30
    activity_probablity_map:
      DoSomething: 0.5
      NoOp: 0.49
      Exit: 0.01
    event_probablity_map:
      correlation_matrix:
        events:
          www.acme.com:
            www.acme.com/pricing: RULE1
            www.acme.com/product: 0.1126
            www.acme.com/product/unified-dashboard: 0.0205
            www.acme.com/product/analytics: 0.0186
            www.acme.com/product/collaboration: 0.0347
            www.acme.com/solutions: 0.0942
            www.acme.com/investors: 0.0164
            www.acme.com/customers: 0.0331
            www.acme.com/integrations: 0.0478
            www.acme.com/resources: 0.0431
            www.acme.com/company: 0.0370
            www.acme.com/schedule-a-demo: RULE13
            Subscribe to Newsletter Form: 0.0113
            www.acme.com/resources/guides: 0.04
            www.acme.com/resources/guides/subscription-billing-and-management-guide: 0.04
            www.acme.com/resources/downloads/infographics/saas-revenue-benchmark-first-100-customers.pdf: 0.04
            www.acme.com/customers/New World: 0.04
            www.acme.com/customers/Old World: 0.04
            www.acme.com/webinars: 0.04
            Logout: 0.1062
          www.acme.com/pricing: 
            www.acme.com: 0.113
            www.acme.com/product: 0.1361
            www.acme.com/product/unified-dashboard: 0.0573
            www.acme.com/product/analytics: 0.0689
            www.acme.com/product/collaboration: 0.0315
            www.acme.com/solutions: 0.0981
            www.acme.com/investors: 0.0345
            www.acme.com/customers: 0.0383
            www.acme.com/integrations: 0.0243
            www.acme.com/resources: 0.0114
            www.acme.com/company: 0.0087
            www.acme.com/schedule-a-demo: RULE14
            Subscribe to Newsletter Form: RULE5
            Logout: 0.2158
          www.acme.com/product:
            www.acme.com: 0.0676
            www.acme.com/pricing: 0.1671
            www.acme.com/product/unified-dashboard: 0.1371
            www.acme.com/product/analytics: 0.1489
            www.acme.com/product/collaboration: 0.1582
            www.acme.com/solutions: 0.0349
            www.acme.com/investors: 0.0267
            www.acme.com/customers: 0.0214
            www.acme.com/integrations: 0.0764
            www.acme.com/resources: RULE7
            www.acme.com/company: 0.0057
            www.acme.com/schedule-a-demo: RULE6
            Logout: 0.0838
          www.acme.com/product/unified-dashboard:
            www.acme.com: 0.0374
            www.acme.com/pricing: 0.077
            www.acme.com/product: 0.0214
            www.acme.com/product/analytics: 0.0561
            www.acme.com/product/collaboration: 0.0647
            www.acme.com/solutions: 0.0278
            www.acme.com/investors: 0.0197
            www.acme.com/customers: 0.0215
            www.acme.com/integrations: 0.0227
            www.acme.com/resources: 0.0385
            www.acme.com/company: 0.0293
            www.acme.com/schedule-a-demo: 0.0071
            Subscribe to Newsletter Form: 0.0387
            Logout: 0.5381
          www.acme.com/product/analytics:
            www.acme.com: 0.0367
            www.acme.com/product: 0.0264
            www.acme.com/pricing: 0.0940
            www.acme.com/product/unified-dashboard: 0.087
            www.acme.com/product/collaboration: 0.0691
            www.acme.com/solutions: 0.0771
            www.acme.com/investors: 0.0157
            www.acme.com/customers: 0.0195
            www.acme.com/integrations: 0.0217
            www.acme.com/resources: 0.0334
            www.acme.com/company: 0.0243
            www.acme.com/schedule-a-demo: 0.0097
            Subscribe to Newsletter Form: 0.0487
            Logout: 0.4367
          www.acme.com/product/collaboration:
            www.acme.com: 0.0478
            www.acme.com/product: 0.0394
            www.acme.com/pricing: 0.0820
            www.acme.com/product/unified-dashboard: 0.0883
            www.acme.com/product/analytics: 0.1027
            www.acme.com/solutions: 0.0372
            www.acme.com/investors: 0.0347
            www.acme.com/customers: 0.0297
            www.acme.com/integrations: 0.0417
            www.acme.com/resources: 0.0523
            www.acme.com/company: 0.0134
            www.acme.com/schedule-a-demo: 0.0078
            Subscribe to Newsletter Form: 0.0291
            Logout: 0.3939
          www.acme.com/solutions:
            www.acme.com: 0.0581
            www.acme.com/pricing: 0.1234
            www.acme.com/product: 0.1453
            www.acme.com/product/unified-dashboard: 0.0276
            www.acme.com/product/analytics: 0.0187
            www.acme.com/product/collaboration: 0.0394
            www.acme.com/investors: 0.0147
            www.acme.com/customers: 0.0172
            www.acme.com/integrations: 0.0092
            www.acme.com/resources: 0.0371
            www.acme.com/company: 0.047
            www.acme.com/schedule-a-demo: 0.0504
            Subscribe to Newsletter Form: 0.0257
            Logout: 0.3862
          www.acme.com/investors:
            www.acme.com: 0.0479
            www.acme.com/pricing: 0.079
            www.acme.com/product: 0.056
            www.acme.com/product/unified-dashboard: 0.0372
            www.acme.com/product/analytics: 0.0337
            www.acme.com/product/collaboration: 0.0315
            www.acme.com/solutions: 0.0267
            www.acme.com/customers: 0.0178
            www.acme.com/integrations: 0.0164
            www.acme.com/resources: 0.0657
            www.acme.com/company: 0.0146
            www.acme.com/schedule-a-demo: 0.0473
            Subscribe to Newsletter Form: 0.0562
            Logout: 0.47
          www.acme.com/customers:
            www.acme.com: 0.0178
            www.acme.com/pricing: 0.107
            www.acme.com/product: 0.1287
            www.acme.com/product/unified-dashboard: 0.0286
            www.acme.com/product/analytics: 0.0191
            www.acme.com/product/collaboration: 0.0243
            www.acme.com/solutions: 0.0147
            www.acme.com/investors: 0.0353
            www.acme.com/integrations: 0.0293
            www.acme.com/resources: 0.0845
            www.acme.com/company: 0.0478
            www.acme.com/schedule-a-demo: 0.0653
            Subscribe to Newsletter Form: 0.0693
            Schedule A Demo Form: 0.01
            Logout: 0.3183
          www.acme.com/integrations:
            www.acme.com: 0.0093
            www.acme.com/pricing: 0.1071
            www.acme.com/product: 0.0867
            www.acme.com/product/unified-dashboard: 0.0431
            www.acme.com/product/analytics: 0.0587
            www.acme.com/product/collaboration: 0.0896
            www.acme.com/solutions: 0.0751
            www.acme.com/investors: 0.0387
            www.acme.com/customers: 0.0297
            www.acme.com/resources: 0.1187
            www.acme.com/company: 0.0245
            www.acme.com/schedule-a-demo: RULE11
            Subscribe to Newsletter Form: RULE12
            Logout: 0.2348
          www.acme.com/resources:
            www.acme.com: 0.0687
            www.acme.com/pricing: 0.0453
            www.acme.com/product: 0.0348
            www.acme.com/product/unified-dashboard: 0.0145
            www.acme.com/product/analytics: 0.0529
            www.acme.com/product/collaboration: 0.0897
            www.acme.com/solutions: 0.0593
            www.acme.com/investors: 0.0134
            www.acme.com/customers: 0.0112
            www.acme.com/integrations: 0.0143
            www.acme.com/company: 0.0097
            www.acme.com/schedule-a-demo: RULE8
            Subscribe to Newsletter Form: 0.0567
            Logout: 0.5189
          www.acme.com/company:
            www.acme.com: 0.0181
            www.acme.com/pricing: 0.0471
            www.acme.com/product: 0.0587
            www.acme.com/product/unified-dashboard: 0.0091
            www.acme.com/product/analytics: 0.0173
            www.acme.com/product/collaboration: 0.0287
            www.acme.com/solutions: 0.0131
            www.acme.com/investors: 0.0192
            www.acme.com/customers: 0.0367
            www.acme.com/integrations: 0.0187
            www.acme.com/resources: 0.0678
            www.acme.com/schedule-a-demo: 0.0353
            Subscribe to Newsletter Form: 0.0397
            Logout: 0.5905
          www.acme.com/schedule-a-demo:
            www.acme.com: 0.0467
            www.acme.com/pricing: 0.0689
            www.acme.com/product: 0.0597
            www.acme.com/product/unified-dashboard: 0.0043
            www.acme.com/product/analytics: 0.0057
            www.acme.com/product/collaboration: 0.0097
            www.acme.com/solutions: 0.0498
            www.acme.com/investors: 0.0057
            www.acme.com/customers: 0.0573
            www.acme.com/integrations: 0.0367
            www.acme.com/resources: 0.0147
            www.acme.com/company: 0.0163
            Subscribe to Newsletter Form: 0.0173
            Schedule A Demo Form: RULE2
            Logout: 0.2109
          Schedule A Demo Form:
            Discovery Call Booked: 0.3919
            Logout: 0.6081
          Subscribe to Newsletter Form:
            www.acme.com: 0.1073
            www.acme.com/pricing: 0.1478
            www.acme.com/product: 0.0487
            www.acme.com/product/unified-dashboard: 0.0087
            www.acme.com/product/analytics: 0.0091
            www.acme.com/product/collaboration: 0.0173
            www.acme.com/solutions: 0.0567
            www.acme.com/investors: 0.0047
            www.acme.com/customers: 0.0073
            www.acme.com/integrations: 0.0114
            www.acme.com/resources: 0.0689
            www.acme.com/company: 0.0113
            www.acme.com/schedule-a-demo: 0.0459
            Logout: 0.4549
          Discovery Call Booked:
            Opportunity Created: 0.5804
            Logout: 0.4196
          Opportunity Created:
            Deal Created: 0.5995
            Logout: 0.4005
          Deal Created:
            Deal Won: RULE3
            Deal Lost: 0.7505
          Deal Won:
            Logout: 1.0
          Deal Lost:
            Logout: 1.0
          www.acme.com/resources/guides:
            Schedule A Demo Form: 0.11
            Logout: 0.89
          www.acme.com/resources/guides/subscription-billing-and-management-guide: 
            Schedule A Demo Form: 0.06
            Logout: 0.94
          www.acme.com/resources/downloads/infographics/saas-revenue-benchmark-first-100-customers.pdf:
            Schedule A Demo Form: 0.03
            Logout: 0.97
          www.acme.com/customers/New World:
            Schedule A Demo Form: 0.04
            Logout: 0.96
          www.acme.com/customers/Old World:
            Schedule A Demo Form: 0.12
            Logout: 0.88
          www.acme.com/webinars:
            Schedule A Demo Form: 0.02
            webinars.acme.com/analytics after-covid: 0.5
            Logout: 0.48
          webinars.acme.com/analytics after-covid: 
            Schedule A Demo Form: 0.04
            Logout: 0.96
        seed_events:
          Subscribe to Newsletter Form: 0.0001
          www.acme.com: 0.7
          www.acme.com/company: 0.02
          www.acme.com/customers: 0.005
          www.acme.com/integrations: 0.006
          www.acme.com/investors: 0.004
          www.acme.com/pricing: 0.09
          www.acme.com/product: 0.05
          www.acme.com/product/analytics: 0.0199
          www.acme.com/product/collaboration: 0.02
          www.acme.com/product/unified-dashboard: 0.003
          www.acme.com/resources: 0.02
          www.acme.com/schedule-a-demo: 0.002
          www.acme.com/solutions: 0.06
        exit_events: [Logout]
    event_attributes:
      default:
        -
          key: Page Load Time
          order_level: 1
          values:
            1-2: 0.457
            3-5: 0.317
            6-10: 0.159
            10-30: 0.067
          data_type: Numerical
        -
          key: Page Spent Time
          order_level: 1
          values:
            0-5: 0.343
            6-15: 0.247
            16-30: 0.186
            31-120: 0.159
            120-300: 0.065
          data_type: Numerical
        -
          key: Vertical Scroll Percentage
          order_level: 1
          values:
            0-10: 0.273
            10-40: 0.226
            40-70: 0.298
            70-100: 0.203
          data_type: Numerical
        -
          key: Browser
          order_level: 1
          values:
            Unknown: 0.051
            Internet Explorer: 0.245
            Safari: 0.067
            Firefox: 0.158
            Chrome: 0.479
        -
          key: Device Type
          order_level: 1
          values:
            Unknown: 0.042
            Tablet: 0.097
            Mobile: 0.248
            Desktop: 0.613
        -
          key: Device Model
          order_level: 1
          values:
            iPhone: 0.054
            Mac: 0.049
            Samsung Galaxy: 0.081
            HP: 0.168
            Thinkpad: 0.195
            Others: 0.453
        -
          key: Referrer
          order_level: 1
          values:
            www.google.com: 0.55
            www.linkedin.com: 0.07
            www.capterra.com: 0.10
            www.g2.com: 0.075
            Others: 0.06
            Direct: 0.145
    user_attributes:
      default:  
        -
          key: Industry
          order_level: 1
          values:
            EdTech: 0.16
            FinTech: 0.26
            Healthcare: 0.086
            E-commerce: 0.28
            Automotive: 0.083
            Other: 0.131
        -
          key: Revenue
          order_level: 1
          values:
            1-1: 0.204
            2-5: 0.159
            6-10: 0.127
            11-25: 0.148
            26-50: 0.087
            51-100: 0.057
            100-200: 0.031
            0-0: 0.187
          data_type: Numerical
        -
          key: Country
          order_level: 1
          values:
            US: 0.385
            UK: 0.207
            GERMANY: 0.156
            FRANCE: 0.132
            AUSTRALIA: 0.054
            OTHERS: 0.066
        -
          key: Number of Employees
          order_level: 1
          values:
            1-5: 0.107
            6-25: 0.263
            26-50: 0.247
            51-100: 0.197
            101-500: 0.052
            500-1000: 0.038
            0-0: 0.096
          data_type: Numerical
        -
          key: Number of Sessions
          order_level: 1
          values:
            1-1: 0.304
            2-4: 0.343
            5-8: 0.144
            9-12: 0.097
            13-20: 0.069
            20-30: 0.043
          data_type: Numerical
        -
          key: Time Spent on Site
          order_level: 1
          values:
            1-1: 0.25
            2-4: 0.35
            5-8: 0.16
            9-15: 0.11
            16-30: 0.07
            31-60: 0.04
            60-100: 0.02
          data_type: Numerical
        -
          key: Page Count
          order_level: 1
          values:
            1-1: 0.244
            2-4: 0.313
            5-8: 0.257
            9-15: 0.136
            16-25: 0.035
            26-30: 0.015
          data_type: Numerical
        -
          key: Initial_Campaign
          order_level: 1
          values:  
            Competitor: 0.127
            Brand: 0.183
            BOF: 0.047
            CXO: 0.041
            Pricing: 0.052
            Features: 0.076
            None: 0.474
      custom:
      -
          key: Job Title
          order_level: 1
          values:  
            CEO: 0.065
            VP SALES: 0.178
            VP Product: 0.134
            CTO: 0.214
            CMO: 0.247
            CFO: 0.153
            Others: 0.009
    set_attributes: true 
    rules:
      RULE1:
        real_time_wait: 10
        overall_probablity: 0.1578
        attribute_weights:
          -
            probablity: 0.18147
            attributes: 
              Industry: 
                -
                  FinTech
      RULE2:
        real_time_wait:
        overall_probablity: 0.3963
        attribute_weights:
          -
            probablity: 0.43593
            attributes: 
              Industry: 
                -
                  EdTech
          -
            probablity: 0.31704
            attributes: 
              Industry: 
                -
                  Healthcare
      RULE3:
        real_time_wait:
        overall_probablity: 0.2495
        attribute_weights:
          -
            probablity: 0.2994
            attributes: 
              Revenue: 
                -
                  26-50
      RULE5:
        real_time_wait:
        overall_probablity: 0.0351
        attribute_weights:
          -
            probablity: 0.04563
            attributes: 
              Country: 
                -
                  UK
      RULE6:
        real_time_wait:
        overall_probablity: 0.0681
        attribute_weights:
          -
            probablity: 0.08172
            attributes: 
              Country: 
                -
                  France
      RULE7:
        real_time_wait:
        overall_probablity: 0.0041
        attribute_weights:
          -
            probablity: 0.00533
            attributes: 
              Country: 
                -
                  US
      RULE8:
        real_time_wait:
        overall_probablity: 0.0106
        attribute_weights:
          -
            probablity: 0.01325
            attributes: 
              Country: 
                -
                  US
      RULE11:
        real_time_wait:
        overall_probablity: 0.0675
        attribute_weights:
          -
            probablity: 0.081
            attributes: 
              Page Count: 
                -
                  9-15
      RULE12:
        real_time_wait:
        overall_probablity: 0.0165
        attribute_weights:
          -
            probablity: 0.018975
            attributes: 
              Page Count: 
                -
                  16-30
      RULE13:
        real_time_wait:
        overall_probablity:  0.0267
        attribute_weights:
          -
            probablity: 0.033375
            attributes: 
              Number of Employees: 
                -
                  6-25
      RULE14:
        real_time_wait:
        overall_probablity: 0.1270
        attribute_weights:
          -
            probablity: 0.0508
            attributes: 
              Number of Sessions: 
                -
                  1-1
          -
            probablity: 0.1524
            attributes: 
              Time Spent on Site: 
                -
                  9-15
          -
            probablity: 0.1397
            attributes: 
              Time Spent on Site: 
                -
                  16-30
