apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    layer: adwords-etl-debug
    env: production
    project: factors-production    
    nodePool: default-pool
  name: adwords-etl-debug
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      layer: adwords-etl-debug
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        layer: adwords-etl-debug
        nodePool: default-pool
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
      - name: adwords-etl-debug
        image: us.gcr.io/factors-production/adwords-etl-debug:v0.51
        volumeMounts:
        - name: workdir
          mountPath: /usr/local/var/factors/config
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
          requests:
            memory: "500Mi"
            cpu: "0.5"
        securityContext: {}
        args:
          - --env
          - $(ENV)
          - --oauth_secret
          - $(GOOGLE_OAUTH_SECRET)
          - --developer_token
          - $(GOOGLE_ADWORDS_DEVELOPER_TOKEN)
          - --data_service_host
          - $(DATA_SERVICE_HOST_URL)
        envFrom:
        - configMapRef:
            name: config-adwordsserver
        - configMapRef:
            name: config-env
        - secretRef:
            name: secret-google
      volumes:
      - name: workdir
        emptyDir: {}
