apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    layer: appserver-memsql
    env: production
    project: factors-production
    nodePool: default-pool
  name: appserver-memsql
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      layer: appserver-memsql
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:      
      labels:
        layer: appserver-memsql
        nodePool: default-pool
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
      - name: appserver-memsql
        image: us.gcr.io/factors-production/app-server:d565985f1-2626
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: workdir
          mountPath: /usr/local/var/factors/config
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          limits:
            memory: "5Gi"
            cpu: "1"
          requests:
            memory: "500Mi"
            cpu: "0.5"
        securityContext: {}
        readinessProbe:
          httpGet:
            path: /mql/status?s=k8_rp
            scheme: HTTP
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /mql/status?s=k8_lp
            scheme: HTTP
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        args:          
          - --customer_enabled_projects_wi
          - 399,594,559,628,616,645,640,641,695,699
          - --env
          - $(ENV)
          - --app_name
          - appserver_memsql
          - --api_http_port
          - $(API_HTTP_PORT)
          - --etcd
          - $(ETCD)
          - --memsql_host
          - $(MEMSQL_HOST)
          - --memsql_port
          - $(MEMSQL_PORT)
          - --memsql_name
          - $(MEMSQL_DB)
          - --memsql_user
          - $(MEMSQL_OLAP_USER)
          - --memsql_pass
          - $(MEMSQL_PASSWORD)
          - --memsql_cert
          - $(MEMSQL_CERTIFICATE)
          - --primary_datastore
          - memsql
          - --memsql_max_open_connections
          - "500"
          - --memsql_max_idle_connections
          - "0"
          - --redis_host
          - $(REDIS_HOST)
          - --redis_port
          - $(REDIS_PORT)
          - --redis_host_ps
          - $(PERSISTENT_REDIS_HOST)
          - --redis_port_ps
          - $(PERSISTENT_REDIS_PORT)
          - --geo_loc_path
          - $(GEO_LOC_FILE_PATH)
          - --api_domain
          - $(API_DOMAIN)
          - --app_domain
          - $(APP_DOMAIN)
          - --app_old_domain
          - $(APP_OLD_HOST_URL)
          - --aws_region
          - $(AWS_REGION)
          - --aws_key
          - $(AWS_KEY)
          - --aws_secret
          - $(AWS_SECRET)
          - --email_sender
          - $(EMAIL_SENDER)
          - --login_token_map
          - $(LOGIN_TOKEN_MAP)
          - --admin_login_email
          - $(ADMIN_LOGIN_EMAIL)
          - --admin_login_token
          - $(ADMIN_LOGIN_TOKEN)
          - --skip_track_project_ids
          - $(SKIP_TRACK_PROJECT_IDS)
          - --facebook_app_id
          - $(FACEBOOK_APP_ID)
          - --facebook_app_secret
          - $(FACEBOOK_APP_SECRET)
          - --linkedin_client_id
          - $(LINKEDIN_CLIENT_ID)
          - --linkedin_client_secret
          - $(LINKEDIN_CLIENT_SECRET)
          - --salesforce_app_id
          - $(SALESFORCE_APP_ID)
          - --salesforce_app_secret
          - $(SALESFORCE_APP_SECRET)
          - --device_detector_path
          - $(DEVICE_DETECTOR_DATA_PATH)
          - --sentry_dsn
          - $(SENTRY_DSN)
          - --gcp_project_id
          - $(GCP_PROJECT_ID)
          - --gcp_project_location
          - $(GCP_PROJECT_LOCATION)
          - --blocked_sdk_request_project_tokens
          - 5w62sncn48ohs9nl9fymkad3ewcked23
          - --cache_look_up_range_projects
          - 336:20190930
          - --lookback_window_event_user_cache
          - "20"
          - --attribution_debug
          - "0"
          - --project_analytics_whitelisted_uuids
          - 1b993a1b-8a76-4ddd-a827-fa3c579ba8b9
          - --allow_smart_event_rule_creation
          - --bucket_name
          - $(BUCKET_NAME)
          - --disable_dashboard_query_db_execution
          - --fivetran_group_id
          - $(FIVETRAN_GROUPID)
          - --fivetran_license_key
          - $(FIVETRAN_LICENCE_KEY)
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP              
        envFrom:
        - configMapRef:
            name: config-appserver
        - configMapRef:
            name: config-etcd
        - configMapRef:
            name: config-env
        - configMapRef:
            name: config-postgres
        - configMapRef:
            name: config-memsql
        - configMapRef:
            name: config-redis
        - configMapRef:
            name: config-persistent-redis
        - configMapRef:
            name: config-add-session-job
        - secretRef:
            name: secret-postgres
        - secretRef:
            name: secret-memsql
        - secretRef:
            name: secret-aws
        - secretRef:
            name: secret-facebook
        - secretRef:
            name: secret-linkedin
        - secretRef:
            name: secret-salesforce
        - secretRef:
            name: secret-login-token
        - secretRef:
            name: secret-sentry
        - configMapRef:
            name: config-bucket
        - secretRef:
            name: secret-fivetran
      initContainers:
      - name: fetch-geolocation-file
        image: google/cloud-sdk:229.0.0-alpine
        command:
        - gsutil
        - cp
        - gs://factors-production/GeoLite2-City.mmdb
        - /workdir/GeoLite2-City.mmdb
        volumeMounts:
        - name: workdir
          mountPath: "/workdir"
      - name: fetch-device-detector-data
        image: google/cloud-sdk:229.0.0-alpine
        command:
        - gsutil 
        - rsync 
        - -r 
        - gs://factors-production/device_detector_regexs
        - /workdir
        volumeMounts:
        - name: workdir
          mountPath: "/workdir"
      volumes:
      - name: workdir
        emptyDir: {}
