apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    layer: integration-request-worker
    env: production
    project: factors-production
    nodePool: workers-pool
  name: integration-request-worker
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      layer: integration-request-worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:      
      labels:
        layer: integration-request-worker
        nodePool: workers-pool
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: workers-pool
      containers:
      - name: integration-request-worker
        image: us.gcr.io/factors-production/integration-request-worker:v1.13-1d6b430-721
        volumeMounts:
        - name: workdir
          mountPath: /usr/local/var/factors/config
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          requests:
            memory: "100M"
        securityContext: {}
        args:
          - --env
          - $(ENV)
          - --db_host
          - $(DB_HOST)
          - --db_port
          - $(DB_PORT)
          - --db_name
          - $(POSTGRES_DB)
          - --db_user
          - $(POSTGRES_USER)
          - --db_pass
          - $(POSTGRES_PASSWORD)
          - --redis_host
          - $(REDIS_HOST)
          - --redis_port
          - $(REDIS_PORT)
          - --queue_redis_host
          - $(QUEUE_REDIS_HOST)
          - --queue_redis_port
          - $(QUEUE_REDIS_PORT)
          - --geo_loc_path
          - $(GEO_LOC_FILE_PATH)
          - --worker_concurrency
          - "15"
          - --device_detector_path
          - $(DEVICE_DETECTOR_DATA_PATH)
          - --sentry_dsn
          - $(SENTRY_DSN)
          - --redis_host_ps
          - $(PERSISTENT_REDIS_HOST)
          - --redis_port_ps
          - $(PERSISTENT_REDIS_PORT)
          - --gcp_project_id
          - $(GCP_PROJECT_ID)
          - --gcp_project_location
          - $(GCP_PROJECT_LOCATION)
          - --segment_excluded_customer_user_ids
          - 576:User Identify
          - --allow_support_for_user_properties_in_identify_call
          - "2"
          - --cache_with_sorted_set
        envFrom:
        - configMapRef:
            name: config-appserver
        - configMapRef:
            name: config-env
        - configMapRef:
            name: config-postgres
        - configMapRef:
            name: config-redis
        - configMapRef:
            name: config-persistent-redis
        - configMapRef:
            name: config-queue-redis
        - configMapRef:
            name: config-add-session-job
        - secretRef:
            name: secret-postgres
        - secretRef:
            name: secret-sentry
      initContainers:
      - name: fetch-geolocation-file
        image: google/cloud-sdk:229.0.0-alpine
        command:
        - gsutil
        - cp
        - gs://factors-production/GeoLite2-City.mmdb
        - /workdir/GeoLite2-City.mmdb
        volumeMounts:
        - name: workdir
          mountPath: "/workdir"
      - name: fetch-device-detector-data
        image: google/cloud-sdk:229.0.0-alpine
        command:
        - gsutil 
        - rsync 
        - -r 
        - gs://factors-production/device_detector_regexs
        - /workdir
        volumeMounts:
        - name: workdir
          mountPath: "/workdir"
      volumes:
      - name: workdir
        emptyDir: {}
