apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    layer: integration-request-worker-dup
    env: production
    project: factors-production
    nodePool: persistent-pool-standard
  name: integration-request-worker-dup
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      layer: integration-request-worker-dup
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:      
      labels:
        layer: integration-request-worker-dup
        nodePool: persistent-pool-standard
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: persistent-pool-standard
      containers:
      - name: integration-request-worker-dup
        image: us.gcr.io/factors-production/integration-request-worker:f75aa8d27-1806
        volumeMounts:
        - name: workdir
          mountPath: /usr/local/var/factors/config
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          requests:
            memory: "100M"
        securityContext: {}
        args:
          - --env
          - $(ENV)
          - --db_host
          - $(DB_HOST_CLONE)
          - --db_port
          - $(DB_PORT)
          - --db_name
          - $(POSTGRES_DB)
          - --db_user
          - $(POSTGRES_USER)
          - --db_pass
          - $(POSTGRES_PASSWORD)
          - --redis_host
          - $(REDIS_HOST_2)
          - --redis_port
          - $(REDIS_PORT_2)
          - --redis_host_ps
          - $(REDIS_HOST_2)
          - --redis_port_ps
          - $(REDIS_PORT_2)
          - --queue_redis_host
          - $(QUEUE_REDIS_HOST)
          - --queue_redis_port
          - $(QUEUE_REDIS_PORT)
          - --dup_queue_redis_host
          - $(DUP_QUEUE_REDIS_HOST)
          - --dup_queue_redis_port
          - $(DUP_QUEUE_REDIS_PORT)
          - --geo_loc_path
          - $(GEO_LOC_FILE_PATH)
          - --worker_concurrency
          - "10"
          - --device_detector_path
          - $(DEVICE_DETECTOR_DATA_PATH)
          - --sentry_dsn
          - $(SENTRY_DSN)
          - --gcp_project_id
          - $(GCP_PROJECT_ID)
          - --gcp_project_location
          - $(GCP_PROJECT_LOCATION)
          - --ontable_user_properties_allowed_projects
          - "*"
          - --deprecate_user_properties_table_read_projects
          - "*"
          - --enable_sdk_and_integration_request_queue_duplication
        envFrom:
        - configMapRef:
            name: config-appserver
        - configMapRef:
            name: config-env
        - configMapRef:
            name: config-postgres
        - configMapRef:
            name: config-redis
        - configMapRef:
            name: config-persistent-redis
        - configMapRef:
            name: config-add-session-job
        - secretRef:
            name: secret-postgres
        - secretRef:
            name: secret-sentry
        - configMapRef:
            name: config-queue-redis
      initContainers:
      - name: fetch-geolocation-file
        image: google/cloud-sdk:229.0.0-alpine
        command:
        - gsutil
        - cp
        - gs://factors-production/GeoLite2-City.mmdb
        - /workdir/GeoLite2-City.mmdb
        volumeMounts:
        - name: workdir
          mountPath: "/workdir"
      - name: fetch-device-detector-data
        image: google/cloud-sdk:229.0.0-alpine
        command:
        - gsutil 
        - rsync 
        - -r 
        - gs://factors-production/device_detector_regexs
        - /workdir
        volumeMounts:
        - name: workdir
          mountPath: "/workdir"
      volumes:
      - name: workdir
        emptyDir: {}
