apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    layer: patternserver
    env: production
    project: factors-production
    nodePool: default-pool
  name: patternserver
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      layer: patternserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:      
      labels:
        layer: patternserver
        nodePool: default-pool
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
      - name: patternserver
        image: us.gcr.io/factors-production/pattern-server:v0.13-beta_a8862cc
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8100
        volumeMounts:
        - name: workdir
          mountPath: /usr/local/var/factors
        resources:
          requests:
            memory: 10Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext: {}
        readinessProbe:
          tcpSocket:
            port: 8100
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8100
          initialDelaySeconds: 10
          periodSeconds: 10
        args:
          - --env
          - $(ENV)
          - --ip
          - $(MY_POD_IP)
          - --ps_rpc_port
          - $(PS_RPC_PORT)
          - --ps_http_port
          - $(PS_HTTP_PORT)
          - --etcd
          - $(ETCD)
          - --bucket_name
          - $(BUCKET_NAME)
          - --disk_dir
          - $(DISK_DIR)
          - --chunk_cache_size
          - $(CHUNK_CACHE_SIZE)
          - --event_info_cache_size
          - $(EVENT_INFO_CACHE_SIZE)
          - --sentry_dsn
          - $(SENTRY_DSN)
 - --memsql_host
          - $(MEMSQL_HOST)
          - --memsql_port
          - $(MEMSQL_PORT)
          - --memsql_name
          - $(MEMSQL_DB)
          - --memsql_user
          - $(MEMSQL_OLTP_USER)
          - --memsql_pass
          - $(MEMSQL_PASSWORD)
          - --memsql_cert
          - $(MEMSQL_CERTIFICATE)
          - --primary_datastore
          - memsql
          - --memsql_host
          - $(MEMSQL_HOST)
          - --memsql_port
          - $(MEMSQL_PORT)
          - --memsql_name
          - $(MEMSQL_DB)
          - --memsql_user
          - $(MEMSQL_USER)
          - --memsql_pass
          - $(MEMSQL_PASSWORD)
          - --memsql_cert
          - $(MEMSQL_CERTIFICATE)
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: config-patternserver
        - configMapRef:
            name: config-etcd
        - configMapRef:
            name: config-env
        - configMapRef:
            name: config-bucket
        - secretRef:
            name: secret-sentry
        - configMapRef:
            name: config-memsql
        - secretRef:
            name: secret-memsql
      volumes:
      - name: workdir
        emptyDir: {}
