apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    layer: redis-2
    env: production
    project: factors-production
    nodePool: shared-persistent-pool
  name: redis-2
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      layer: redis-2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:      
      labels:
        layer: redis-2
        nodePool: shared-persistent-pool
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: shared-persistent-pool
      containers:
      - name: redis-2
        image: us.gcr.io/factors-production/redis:v0.01-8b7c088
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: workdir
          mountPath: /usr/local/var/factors
        resources:
          requests:
            memory: "1G"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext: {}
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: workdir
        emptyDir: {}