apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    layer: sdkserver
    env: production
    project: factors-production
    nodePool: persistent-pool-standard
  name: sdkserver
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      layer: sdkserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:      
      labels:
        layer: sdkserver
        nodePool: persistent-pool-standard
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: persistent-pool-standard
      containers:
      - name: sdkserver
        image: us.gcr.io/factors-production/sdk-server:v1.13-1d6b430-721
        ports:
        - containerPort: 8085
        volumeMounts:
        - name: workdir
          mountPath: /usr/local/var/factors/config
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          requests:
            memory: "100M"
        securityContext: {}
        readinessProbe:
          tcpSocket:
            port: 8085
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8085
          initialDelaySeconds: 10
          periodSeconds: 10
        args:
          - --env
          - $(ENV)
          - --port
          - $(SDK_SERVER_PORT)
          - --memsql_host
          - $(MEMSQL_HOST)
          - --memsql_port
          - $(MEMSQL_PORT)
          - --memsql_name
          - $(MEMSQL_DB)
          - --memsql_user
          - $(MEMSQL_OLTP_USER)
          - --memsql_pass
          - $(MEMSQL_PASSWORD)
          - --memsql_cert
          - $(MEMSQL_CERTIFICATE)
          - --redis_host
          - $(REDIS_HOST)
          - --redis_port
          - $(REDIS_PORT)
          - --queue_redis_host
          - $(QUEUE_REDIS_HOST)
          - --queue_redis_port
          - $(QUEUE_REDIS_PORT)
          - --dup_queue_redis_host
          - $(DUP_QUEUE_REDIS_HOST)
          - --dup_queue_redis_port
          - $(DUP_QUEUE_REDIS_PORT)
          - --geo_loc_path
          - $(GEO_LOC_FILE_PATH)
          - --sdk_request_queue_project_tokens
          - $(SDK_REQUEST_QUEUE_PROJECT_TOKENS)
          - --segment_request_queue_project_tokens
          - $(SEGMENT_REQUEST_QUEUE_PROJECT_TOKENS)
          - --device_detector_path
          - $(DEVICE_DETECTOR_DATA_PATH)
          - --sentry_dsn
          - $(SENTRY_DSN)
          - --redis_host_ps
          - $(PERSISTENT_REDIS_HOST)
          - --redis_port_ps
          - $(PERSISTENT_REDIS_PORT)
          - --gcp_project_id
          - $(GCP_PROJECT_ID)
          - --gcp_project_location
          - $(GCP_PROJECT_LOCATION)
          - --blocked_sdk_request_project_tokens
          - 5w62sncn48ohs9nl9fymkad3ewcked23
          - --allow_support_for_user_properties_in_identify_call
          - "2"
          - --cache_with_sorted_set
          - --enable_sdk_and_integration_request_queue_duplication
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP              
        envFrom:
        - configMapRef:
            name: config-sdkserver
        - configMapRef:
            name: config-appserver
        - configMapRef:
            name: config-env
        - configMapRef:
            name: config-memsql        
        - configMapRef:
            name: config-redis
        - configMapRef:
            name: config-persistent-redis
        - configMapRef:
            name: config-queue-redis
        - configMapRef:
            name: config-add-session-job
        - secretRef:
            name: secret-sentry
        - secretRef:
            name: secret-memsql
      initContainers:
      - name: fetch-geolocation-file
        image: google/cloud-sdk:229.0.0-alpine
        command:
        - gsutil
        - cp
        - gs://factors-production/GeoLite2-City.mmdb
        - /workdir/GeoLite2-City.mmdb
        volumeMounts:
        - name: workdir
          mountPath: "/workdir"    
      - name: fetch-device-detector-data
        image: google/cloud-sdk:229.0.0-alpine
        command:
        - gsutil 
        - rsync 
        - -r 
        - gs://factors-production/device_detector_regexs
        - /workdir
        volumeMounts:
        - name: workdir
          mountPath: "/workdir"
      volumes:
      - name: workdir
        emptyDir: {}
