FROM golang:1.14-alpine AS builder

WORKDIR /go/src/data_simulator
ADD /data_simulator .
RUN go build -o $GOPATH/bin/datafeeder $GOPATH/src/data_simulator/datafeeder/data_feeder.go

# Create stripped down version without go and source code
FROM alpine:3.7
COPY --from=builder /go/bin/datafeeder /go/bin/datafeeder
ENTRYPOINT ["/go/bin/datafeeder"]