apiVersion: v1
kind: ConfigMap
metadata:
  name: config-add-session-job
  labels:
    env: staging
    project: factors-staging
data:
  ADD_SESSION_NUM_ROUTINES: "10"
  ADD_SESSION_MAX_LOOKBACK_HOURS: "24"