apiVersion: v1
kind: ConfigMap
metadata:
  name: config-appserver
data:
  API_HTTP_PORT: "8080"
  GEO_LOC_FILE_PATH: "/usr/local/var/factors/config/GeoLite2-City.mmdb"
  EMAIL_SENDER: "support@factors.ai"