apiVersion: v1
kind: ConfigMap
metadata:
  name: config-beamondataflow
  labels:
    env: staging
    project: factors-staging
data:
  BEAM_RUNNER: "dataflow"
  BEAM_PROJECT: "factors-staging"
  BEAM_REGION: "us-west1"
  BEAM_ZONE: "us-west1-b"
  BEAM_TEMP_LOCATION: "gs://factors-staging-misc/beam/tmp/"
  BEAM_STAGIN_LOCATION: "gs://factors-staging-misc/beam/binaries/"
  BEAM_WORKER_HARNESS_IMAGE: "apache/beam_go_sdk:latest"
  BEAM_SUBNETWORK: "regions/us-west1/subnetworks/us-west-1-factors-staging-subnet-1"
