apiVersion: v1
kind: ConfigMap
metadata:
  name: config-postgres
  labels:
    env: staging
    project: factors-staging
data:
  DB_HOST: "localhost"
  DB_PORT: "5432"
  POSTGRES_DB: "autometa"
  DB_HOST_CLONE: "localhost"