apiVersion: v1
kind: ConfigMap
metadata:
  name: config-redis
  labels:
    env: staging
    project: factors-staging
data:
  REDIS_HOST: "localhost"
  REDIS_PORT: "6379"
  REDIS_HOST_2: "localhost"
  REDIS_PORT_2: "1379"