FROM python:3.8-slim as base

ENV PYTHONPATH "${PYTHONPATH}:/usr/local/var/factors/:/usr/local/var/factors/chat_factors/:/usr/local/var/factors/chat_factors/chatgpt_poc/:/usr/local/var/factors/chat_factors/chatgpt_poc/chat_jobs/"

RUN mkdir -p /usr/local/var/factors
WORKDIR /usr/local/var/factors
ADD . ./
RUN  pip install --upgrade pip && pip install -r adwords_requirements.txt && pip install -r chat_requirements.txt

FROM python:3.8-slim

ENV PYTHONPATH "${PYTHONPATH}:/usr/local/var/factors/:/usr/local/var/factors/chat_factors/:/usr/local/var/factors/chat_factors/chatgpt_poc/:/usr/local/var/factors/chat_factors/chatgpt_poc/chat_jobs/"
WORKDIR /usr/local/var/factors
ADD . ./
COPY --from=base /usr/local/lib/python3.8/site-packages/ /usr/local/lib/python3.8/site-packages/

# Install necessary dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libopenblas-dev \
    liblapack-dev \
    libblas-dev \
    libatlas-base-dev \
    libffi-dev \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["python", "./chat_factors/chatgpt_poc/chat_jobs/create_chat_data.py"]