apiVersion: v1
kind: Secret
metadata:
   name: secret-login-token
   labels:
    env: production
    project: factors-production
type: Opaque
data:
   ADMIN_LOGIN_EMAIL: ""
   ADMIN_LOGIN_TOKEN: ""
   LOGIN_TOKEN_MAP: ""