
name: pattern-mine-GKE

on:
  workflow_dispatch:
    inputs:
      image_id:
        description: 'image id'
        required: true
        default: 'test'
      env_name:
        description: 'env'
        required: true
        default: 'staging'
      build_name:
        description: 'build name'
        required: true
        default: ''
        
env:
  PATH_TO_FACTORS : /home/runner/work/factors
      


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - run: go version
        
      
    - name : set env - staging
      if : ${{ github.event.inputs.env_name=='staging'}}
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GKE_STAGING_SA_KEY }}
        project_id: ${{ secrets.GKE_PRODUCTION_PROJECT }}



    - name : set env - production - gcloud - CLI
      if : ${{ github.event.inputs.env_name=='production'}}
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GKE_PRODUCTION_SA_KEY }}
        project_id: ${{ secrets.GKE_PRODUCTION_PROJECT }}




    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker
    
    - name: Build Pattern Mine 
      env : 
        GOPATH: ${{ env.PATH_TO_FACTORS }}/factors/backend
        IMAGE_NAME: ${{ github.event.inputs.image_id}}
      working-directory: ${{ env.GOPATH}}/src
      run : TAG=${{ env.IMAGE_NAME}} ENV=${{ github.event.inputs.env_name}} make pack-pattern-mine

    - name: Publish Pattern Mine 
      env : 
        GOPATH: ${{ env.PATH_TO_FACTORS }}/factors/backend
        IMAGE_NAME: ${{ github.event.inputs.image_id}}
      working-directory: ${{ env.GOPATH}}/src
      run : TAG=${{ env.IMAGE_NAME}} ENV=${{ github.event.inputs.env_name}} make upload-pattern-mine
