name: Validate Commit Count

on:
  workflow_run:
    workflows: ["Validate Pull Request"]
    types:
      - completed

jobs:
  commit-count:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v3

      - name: check commit count
        working-directory: ./
        run: bash check_commits.sh

