name: Validate Pull Request

on:
  pull_request:
    branches: [master, staging, release]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20.2"

      - name: check compilation
        working-directory: backend/src/factors/tests
        run: go vet -composites=false .

      - name: run tests
        working-directory: backend/src/factors/tests/gha_tests
        run: go test -timeout 30s

      - name: check merge conflicts
        working-directory: ./
        run: bash check_conflicts.sh
